// Copyright (c) Google Inc. 2009
// All rights reserved.
// This file is automatically generated by GRIT. Do not edit.
// Built on Tue Feb 17 20:18:48 2009

#pragma once

#define IDR_DEBUGGER_SHELL_JS 14537
#define IDR_DEBUGGER_HTML 14538
#define IDR_DEBUGGER_CSS 14539
#define IDR_DEBUGGER_JS 14540
