// Copyright (c) Google Inc. 2009
// All rights reserved.
// This file is automatically generated by GRIT. Do not edit.
// Built on Tue Feb 24 18:00:59 2009

#pragma once

#define IDR_DIR_HEADER_HTML 11170
