// Copyright (c) Google Inc. 2009
// All rights reserved.
// This file is automatically generated by GRIT. Do not edit.
// Built on Tue Feb 17 20:18:46 2009

#pragma once

#define IDR_BROKENIMAGE 9729
#define IDR_TICKMARK_DASH 9730
#define IDR_FEED_PREVIEW 9731
#define IDR_PAN_SCROLL_ICON 9732
#define IDR_TEXTAREA_RESIZER 9733
#define IDC_ALIAS 9734
#define IDC_CELL 9735
#define IDC_COLRESIZE 9736
#define IDC_COPYCUR 9737
#define IDC_ROWRESIZE 9738
#define IDC_VERTICALTEXT 9739
#define IDC_ZOOMIN 9740
#define IDC_ZOOMOUT 9741
#define IDC_PAN_MIDDLE 9742
#define IDC_PAN_NORTH 9743
#define IDC_PAN_NORTH_EAST 9744
#define IDC_PAN_EAST 9745
#define IDC_PAN_SOUTH_EAST 9746
#define IDC_PAN_SOUTH 9747
#define IDC_PAN_SOUTH_WEST 9748
#define IDC_PAN_WEST 9749
#define IDC_PAN_NORTH_WEST 9750
