/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef FIRE_H
#define FIRE_H

wchar_t* FIRE[] = {
L"var h,n=this;function aa(a,b){a=a.split(\".\");b=b||n;for(var c;c=a.shift();)if(b[c])b=b[c];else return null;return b}function p(){}",
L"function q(a){var b=typeof a;if(b==\"object\")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)==\"[object Array]\"||typeof a.length==\"number\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)==\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\")))return\"function\"}else return\"null\";",
L"else if(b==\"function\"&&typeof a.call==\"undefined\")return\"object\";return b}function ba(a){if(a.hasOwnProperty&&a.hasOwnProperty(r))return a[r];a[r]||(a[r]=++ca);return a[r]}var r=\"closure_uid_\"+Math.floor(Math.random()*2147483648).toString(36),ca=0;function s(a,b){function c(){}c.prototype=b.prototype;a.t=b.prototype;a.prototype=new c};var t=Array.prototype,da=t.indexOf?function(a,b,c){return t.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(typeof a==\"string\"){if(typeof b!=\"string\"||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};function ea(a,b){var c=0;a=String(a).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");b=String(b).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");for(var d=Math.max(a.length,b.length),e=0;c==0&&e<d;e++){var f=a[e]||\"\",j=b[e]||\"\",g=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),o=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var i=g.exec(f)||[\"\",\"\",\"\"],k=o.exec(j)||[\"\",\"\",\"\"];if(i[0].length==0&&k[0].length==0)break;c=u(i[1].length==0?0:parseInt(i[1],10),k[1].length==0?0:parseInt(k[1],10))||u(i[2].length==0,k[2].length==0)||u(i[2],",
L"k[2])}while(c==0)}return c}function u(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var v,w,x,y;function fa(){return n.navigator?n.navigator.userAgent:null}y=x=w=v=false;var z;if(z=fa()){var ga=n.navigator;v=z.indexOf(\"Opera\")==0;w=!v&&z.indexOf(\"MSIE\")!=-1;x=!v&&z.indexOf(\"WebKit\")!=-1;y=!v&&!x&&ga.product==\"Gecko\"}var ha=v,A=w,ia=y,ja=x,ka=n.navigator,la=(ka&&ka.platform||\"\").indexOf(\"Mac\")!=-1,ma,B=\"\",C;",
L"if(ha&&n.opera){var D=n.opera.version;B=typeof D==\"function\"?D():D}else{if(ia)C=/rv\\:([^\\);]+)(\\)|;)/;else if(A)C=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(ja)C=/WebKit\\/(\\S+)/;if(C){var na=C.exec(fa());B=na?na[1]:\"\"}}ma=B;var oa={};function E(a){return a.nodeType==9?a:a.ownerDocument||a.document};function F(){}F.prototype.n=false;F.prototype.g=function(){if(!this.n){this.n=true;this.d()}};F.prototype.d=function(){};function G(a,b){this.type=a;this.currentTarget=this.target=b}s(G,F);G.prototype.d=function(){delete this.type;delete this.target;delete this.currentTarget};G.prototype.k=false;G.prototype.w=true;function H(a,b){a&&this.i(a,b)}s(H,G);h=H.prototype;h.target=null;h.relatedTarget=null;h.offsetX=0;h.offsetY=0;h.clientX=0;h.clientY=0;h.screenX=0;h.screenY=0;h.button=0;h.keyCode=0;h.charCode=0;h.ctrlKey=false;h.altKey=false;h.shiftKey=false;h.metaKey=false;h.v=false;h.o=null;",
L"h.i=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(ia)try{b=b.nodeName&&b}catch(d){b=null}}else if(c==\"mouseover\")b=a.fromElement;else if(c==\"mouseout\")b=a.toElement;this.relatedTarget=b;this.offsetX=a.offsetX!==undefined?a.offsetX:a.layerX;this.offsetY=a.offsetY!==undefined?a.offsetY:a.layerY;this.clientX=a.clientX!==undefined?a.clientX:a.pageX;this.clientY=a.clientY!==undefined?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=",
L"a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c==\"keypress\"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.v=la?a.metaKey:a.ctrlKey;this.o=a;delete this.w;delete this.k};A&&(oa[\"8\"]||(oa[\"8\"]=ea(ma,\"8\")>=0));H.prototype.d=function(){H.t.d.call(this);this.relatedTarget=this.currentTarget=this.target=this.o=null};function pa(){}var qa=0;h=pa.prototype;h.key=0;h.f=false;h.l=false;h.i=function(a,b,c,d,e,f){if(q(a)==\"function\")this.p=true;else if(a&&a.handleEvent&&q(a.handleEvent)==\"function\")this.p=false;else throw Error(\"Invalid listener argument\");this.j=a;this.s=b;this.src=c;this.type=d;this.capture=!!e;this.u=f;this.l=false;this.key=++qa;this.f=false};h.handleEvent=function(a){if(this.p)return this.j.call(this.u||this.src,a);return this.j.handleEvent.call(this.j,a)};function I(a,b){this.q=b;this.b=[];if(a>this.q)throw Error(\"[goog.structs.SimplePool] Initial cannot be greater than max\");for(b=0;b<a;b++)this.b.push(this.a?this.a():{})}s(I,F);I.prototype.a=null;I.prototype.m=null;function ra(a){if(a.b.length)return a.b.pop();return a.a?a.a():{}}function J(a,b){a.b.length<a.q?a.b.push(b):sa(a,b)}function sa(a,b){if(a.m)a.m(b);else if(q(b.g)==\"function\")b.g();else for(var c in b)delete b[c]}",
L"I.prototype.d=function(){I.t.d.call(this);for(var a=this.b;a.length;)sa(this,a.pop());delete this.b};var ta;var ua=(ta=\"ScriptEngine\"in n&&n.ScriptEngine()==\"JScript\")?n.ScriptEngineMajorVersion()+\".\"+n.ScriptEngineMinorVersion()+\".\"+n.ScriptEngineBuildVersion():\"0\";var K,L,M,va,N,O,P,Q;",
L"(function(){function a(){return{c:0,e:0}}function b(){return[]}function c(){function l(za){return j.call(l.src,l.key,za)}return l}function d(){return new pa}function e(){return new H}var f=ta&&!(ea(ua,\"5.7\")>=0),j;va=function(l){j=l};if(f){K=function(l){J(g,l)};L=function(){return ra(o)};M=function(l){J(o,l)};N=function(){J(i,c())};O=function(l){J(k,l)};P=function(){return ra(m)};Q=function(l){J(m,l)};var g=new I(0,600);g.a=a;var o=new I(0,600);o.a=b;var i=new I(0,600);i.a=c;var k=new I(0,600);k.a=",
L"d;var m=new I(0,600);m.a=e}else{K=p;L=b;O=N=M=p;P=e;Q=p}})();var R={},S={},T={},U={};function wa(a){if(!R[a])return false;var b=R[a];if(b.f)return false;var c=b.src,d=b.type,e=b.s,f=b.capture;if(c.removeEventListener){if(c==n||!c.B)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(xa(d),e);c=ba(c);e=S[d][f][c];if(T[c]){var j=T[c],g=da(j,b);g>=0&&t.splice.call(j,g,1);j.length==0&&delete T[c]}b.f=true;e.r=true;ya(d,f,c,e);delete R[a];return true}",
L"function ya(a,b,c,d){if(!d.h)if(d.r){for(var e=0,f=0;e<d.length;e++)if(d[e].f){var j=d[e].s;j.src=null;N(j);O(d[e])}else{if(e!=f)d[f]=d[e];f++}d.length=f;d.r=false;if(f==0){M(d);delete S[a][b][c];S[a][b].c--;if(S[a][b].c==0){K(S[a][b]);delete S[a][b];S[a].c--}if(S[a].c==0){K(S[a]);delete S[a]}}}}function xa(a){if(a in U)return U[a];return U[a]=\"on\"+a}",
L"function Aa(a,b,c,d,e){var f=1;b=ba(b);if(a[b]){a.e--;a=a[b];if(a.h)a.h++;else a.h=1;try{for(var j=a.length,g=0;g<j;g++){var o=a[g];if(o&&!o.f)f&=V(o,e)!==false}}finally{a.h--;ya(c,d,b,a)}}return Boolean(f)}function V(a,b){b=a.handleEvent(b);a.l&&wa(a.key);return b}",
L"va(function(a,b){if(!R[a])return true;a=R[a];var c=a.type,d=S;if(!(c in d))return true;d=d[c];var e,f;if(A){e=b||aa(\"window.event\");b=true in d;var j=false in d;if(b){if(e.keyCode<0||e.returnValue!=undefined)return true;a:{var g=false;if(e.keyCode==0)try{e.keyCode=-1;break a}catch(o){g=true}if(g||e.returnValue==undefined)e.returnValue=true}}g=P();g.i(e,this);e=true;try{if(b){for(var i=L(),k=g.currentTarget;k;k=k.parentNode)i.push(k);f=d[true];f.e=f.c;for(var m=i.length-1;!g.k&&m>=0&&f.e;m--){g.currentTarget=",
L"i[m];e&=Aa(f,i[m],c,true,g)}if(j){f=d[false];f.e=f.c;for(m=0;!g.k&&m<i.length&&f.e;m++){g.currentTarget=i[m];e&=Aa(f,i[m],c,false,g)}}}else e=V(a,g)}finally{if(i){i.length=0;M(i)}g.g();Q(g)}return e}f=new H(b,this);try{e=V(a,f)}finally{f.g()}return e});var Ba=A?0:1,Ca=[\"dragstart\",\"dragexit\",\"mouseover\",\"mouseout\"];",
L"function W(a,b,c){var d=E(a),e=d?d.parentWindow||d.defaultView:window;c=c||{};var f=c.x||0,j=c.y||0,g=c.button||Ba,o=c.bubble||true,i=null;if(da(Ca,b)>=0)i=c.related||null;var k=!!c.alt,m=!!c.control,l=!!c.shift;c=!!c.meta;if(a.fireEvent&&d&&d.createEventObject){a=d.createEventObject();a.altKey=k;a.z=m;a.metaKey=c;a.shiftKey=l;a.clientX=f;a.clientY=j;a.button=g;a.relatedTarget=i}else{a=d.createEvent(\"MouseEvents\");if(a.initMouseEvent)a.initMouseEvent(b,o,true,e,1,0,0,f,j,m,k,l,c,g,i);else{a.initEvent(b,",
L"o,true);a.shiftKey=l;a.metaKey=c;a.altKey=k;a.ctrlKey=m;a.button=g}}return a}function Da(a,b,c){var d=E(a);c=c||{};var e=c.bubble||true,f=!!c.alt,j=!!c.control,g=!!c.shift;c=!!c.meta;if(a.fireEvent&&d&&d.createEventObject){a=d.createEventObject();a.altKey=f;a.A=j;a.metaKey=c;a.shiftKey=g}else{a=d.createEvent(\"HTMLEvents\");a.initEvent(b,e,true);a.shiftKey=g;a.metaKey=c;a.altKey=f;a.ctrlKey=j}return a}var X={};X.mousedown=W;X.mousemove=W;X.mouseout=W;X.mouseover=W;X.mouseup=W;function Ea(a,b,c){c=(X[b]||Da)(a,b,c);if(a.fireEvent){try{(E(a)?E(a).parentWindow||E(a).defaultView:window).event=c}catch(d){}a.fireEvent(\"on\"+b,c)}else a.dispatchEvent(c)}var Y=\"fire\".split(\".\"),Z=n;!(Y[0]in Z)&&Z.execScript&&Z.execScript(\"var \"+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&Ea!==undefined)Z[$]=Ea;else Z=Z[$]?Z[$]:(Z[$]={});",
NULL
};

#endif

/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef FIND_ELEMENT_H
#define FIND_ELEMENT_H

wchar_t* FIND_ELEMENT[] = {
L"var h=this;",
L"function aa(a){var b=typeof a;if(b==\"object\")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)==\"[object Array]\"||typeof a.length==\"number\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)==\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\")))return\"function\"}else return\"null\";else if(b==",
L"\"function\"&&typeof a.call==\"undefined\")return\"object\";return b}function i(a){return typeof a==\"string\"}function j(a){return aa(a)==\"function\"}function ba(a,b){var c=b||h;if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,e);return a.apply(c,f)}}else return function(){return a.apply(c,arguments)}};var k=Array.prototype,l=k.indexOf?function(a,b,c){return k.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(i(a)){if(!i(b)||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},n=k.filter?function(a,b,c){return k.filter.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=[],d=0,g=i(a)?a.split(\"\"):a,m=0;m<e;m++)if(m in g){var A=g[m];if(b.call(c,A,m,a))f[d++]=A}return f};",
L"function o(a,b,c){a:{for(var e=a.length,f=i(a)?a.split(\"\"):a,d=0;d<e;d++)if(d in f&&b.call(c,f[d],d,a)){b=d;break a}b=-1}return b<0?null:i(a)?a.charAt(b):a[b]};function p(a,b){this.width=a;this.height=b}p.prototype.toString=function(){return\"(\"+this.width+\" x \"+this.height+\")\"};function q(a){return a.replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}",
L"function r(a,b){var c=0;a=q(String(a)).split(\".\");b=q(String(b)).split(\".\");for(var e=Math.max(a.length,b.length),f=0;c==0&&f<e;f++){var d=a[f]||\"\",g=b[f]||\"\",m=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),A=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var u=m.exec(d)||[\"\",\"\",\"\"],v=A.exec(g)||[\"\",\"\",\"\"];if(u[0].length==0&&v[0].length==0)break;c=s(u[1].length==0?0:parseInt(u[1],10),v[1].length==0?0:parseInt(v[1],10))||s(u[2].length==0,v[2].length==0)||s(u[2],v[2])}while(c==0)}return c}",
L"function s(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var t,w,x,y;function z(){return h.navigator?h.navigator.userAgent:null}y=x=w=t=false;var B;if(B=z()){var ca=h.navigator;t=B.indexOf(\"Opera\")==0;w=!t&&B.indexOf(\"MSIE\")!=-1;x=!t&&B.indexOf(\"WebKit\")!=-1;y=!t&&!x&&ca.product==\"Gecko\"}var C=t,da=w,ea=y,D=x,E,F=\"\",G;if(C&&h.opera){var H=h.opera.version;F=typeof H==\"function\"?H():H}else{if(ea)G=/rv\\:([^\\);]+)(\\)|;)/;else if(da)G=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(D)G=/WebKit\\/(\\S+)/;if(G){var I=G.exec(z());F=I?I[1]:\"\"}}E=F;var J={};function K(a,b){if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!=\"undefined\")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function L(a){return a.nodeType==9?a:a.ownerDocument||a.document}function M(a){this.g=a||h.document||document}",
L"M.prototype.d=function(a,b,c){var e=this.g;c=c||e;a=a&&a!=\"*\"?a.toUpperCase():\"\";if(c.querySelectorAll&&(a||b)&&(!D||e.compatMode==\"CSS1Compat\"||J[\"528\"]||(J[\"528\"]=r(E,\"528\")>=0)))b=c.querySelectorAll(a+(b?\".\"+b:\"\"));else if(b&&c.getElementsByClassName){e=c.getElementsByClassName(b);if(a){c={};for(var f=0,d=0,g;g=e[d];d++)if(a==g.nodeName)c[f++]=g;c.length=f;b=c}else b=e}else{e=c.getElementsByTagName(a||\"*\");if(b){c={};for(d=f=0;g=e[d];d++){a=g.className;if(typeof a.split==\"function\"&&l(a.split(/\\s+/),",
L"b)>=0)c[f++]=g}c.length=f;b=c}else b=e}return b};M.prototype.contains=K;var N={};N.c=function(a,b,c){return b==c||K(b,a)};N.a=function(a,b,c){if(!b)throw Error(\"No class name specified\");b=q(b);if(b.split(/\\s+/).length>1)throw Error(\"Compound class names not permitted\");var e=L(a),f=c||e;a=(new M(e)).d(\"*\",b);return o(a,function(d){return N.c(d,f,e)})};",
L"N.b=function(a,b,c){if(!b)throw Error(\"No class name specified\");b=q(b);if(b.split(/\\s+/).length>1)throw Error(\"Compound class names not permitted\");var e=L(a),f=c||e;a=(new M(e)).d(\"*\",b);return n(a,function(d){return N.c(d,f,e)})};var O={};O.a=function(a,b,c){a=c||L(a);if(!j(a.querySelector))throw Error(\"CSS selection is not supported\");if(!b)throw Error(\"No selector specified\");if(b.split(/,/).length>1)throw Error(\"Compound selectors not permitted\");b=q(b);return(b=a.querySelector(b))?b:null};O.b=function(a,b,c){a=c||L(a);if(!j(a.querySelectorAll))throw Error(\"CSS selection is not supported\");if(!b)throw Error(\"No selector specified\");if(b.split(/,/).length>1)throw Error(\"Compound selectors not permitted\");b=q(b);return a.querySelectorAll(b)};function P(a,b){var c=L(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(a=c.defaultView.getComputedStyle(a,\"\"))return a[b];return null}",
L"function fa(a){var b=C&&!(J[\"10\"]||(J[\"10\"]=r(E,\"10\")>=0));if((P(a,\"display\")||(a.currentStyle?a.currentStyle.display:null)||a.style.display)!=\"none\")return b?new p(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new p(a.offsetWidth,a.offsetHeight);var c=a.style,e=c.display,f=c.visibility,d=c.position;c.visibility=\"hidden\";c.position=\"absolute\";c.display=\"inline\";if(b){b=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{b=a.offsetWidth;a=a.offsetHeight}c.display=e;c.position=",
L"d;c.visibility=f;return new p(b,a)};function ga(a,b){if(j(a.hasAttribute))if(a.hasAttribute(b))return true;return a[b]!==undefined}var ha=[\"async\",\"autofocus\",\"autoplay\",\"checked\",\"compact\",\"complete\",\"declare\",\"defaultChecked\",\"defaultSelected\",\"defer\",\"disabled\",\"draggable\",\"ended\",\"formNoValidate\",\"hidden\",\"indeterminate\",\"isContentEditable\",\"isMap\",\"loop\",\"multiple\",\"muted\",\"noHref\",\"noResize\",\"noShade\",\"noWrap\",\"noValidate\",\"open\",\"paused\",\"readOnly\",\"required\",\"reversed\",\"scoped\",\"seamless\",\"seeking\",\"selected\",\"visible\",\"willValidate\"];",
L"function Q(a,b){if(!a)throw Error(\"Element has not been specified\");if(!b)throw Error(\"Attribute name must be set\");var c=b.toLowerCase();if(l(ha,b)>=0){if(!ga(a,b))return false;a=a[b];return!!(a&&a!=\"false\")}if(!ga(a,b))return null;if(\"style\"==c){a=a.style;return a.cssText?a.cssText:\"\"}if(\"class\"==c)b=\"className\";if(\"readonly\"==c)b=\"readOnly\";return a[b]===undefined?a.getAttribute(b):a[b]}",
L"function ia(a){if(!a||!a.parentNode)return null;for(a=a.parentNode;a.nodeType!=1&&!(a.nodeType==9||a.nodeType==11);)a=a.parentNode;return a&&a.nodeType==1?a:null}",
L"function ja(a){if(!a)throw new Error(\"No value given for isDisplayed required parameter.\");var b=a;if(b.nodeType!=1)b=ia(a);if(!b)throw new Error(\"Node given does not have a parent element.\");var c=L(b)?L(b).parentWindow||L(b).defaultView:window;function e(d,g){if(c.getComputedStyle)return P(d,g);return d.currentStyle?d.currentStyle[g]:null}function f(d){if(e(d,\"display\")==\"none\")return false;d=ia(d);return!d||f(d)}if(!((b.tagName.toLowerCase()==\"input\"&&b.type.toLowerCase()==\"hidden\"?false:e(b,\"visibility\")!=",
L"\"hidden\")&&f(b)))return false;a=fa(b);return a.height>0&&a.width>0}",
L"function R(a,b,c){if(a.tagName&&a.tagName==\"SCRIPT\")return[b,c];else if(a.tagName&&a.tagName==\"TITLE\")return[c+a.text,\"\"];for(var e=a.childNodes,f=0;f<e.length;f++){var d=e[f];if(d.tagName&&d.tagName==\"PRE\"){b+=S(c);c=\"\";d=R(d,b,\"\",true);b+=d[1]}else if(d.nodeName==\"#text\"){if(ja(d)){d=d.nodeValue;d=d.replace(new RegExp(String.fromCharCode(160),\"gm\"),\" \");c+=d}}else{d=R(d,b,c,false);b=d[0];c=d[1]}}if(a.tagName&&a.tagName==\"BR\"?true:false)if(a.tagName&&a.tagName!=\"PRE\"){b+=S(c)+\"\\n\";c=\"\"}else b+=\"\\n\";",
L"return[b,c]}function S(a){return a.replace(/[\\s\\xa0]+/g,\" \")}function ka(a){return a==\"\\n\"||a==\" \"||a==\"\\t\"||a==\"\\r\"||a==\"\\u00a0\"}function la(a){a=R(a,\"\",\"\",a.tagName==\"PRE\");a=a[0]+S(a[1]);for(var b=0;b<a.length&&ka(a[b]);)++b;for(var c=a.length;c>b&&ka(a[c-1]);)--c;return a.slice(b,c)};var T={};T.a=function(a,b,c){a=L(a);c=c||a;var e=a.getElementById(b);if(!e)return null;if(e.getAttribute(\"id\")==b&&K(c,e))return e;a=a.getElementsByTagName(\"*\");e=a.length;for(var f=0;f<e;f++){var d=a[f];if(d.tagName.toLowerCase()==\"form\"){if(d.attributes.id.nodeValue==b&&K(c,d))return d}else if(Q(d,\"id\")==b&&K(c,d))return d}return null};T.b=function(a,b,c){a=L(a);var e=c||a;c=a.getElementsByTagName(\"*\");return n(c,function(f){return Q(f,\"id\")==b&&K(e,f)})};var U={},V={};U.f=function(a,b,c,e){if(!b&&b!=\"\")throw Error(\"No link text specified\");a=L(a);var f=c||a;c=(new M(a)).d(\"A\");return o(c,function(d){var g=la(d);if(e&&g.indexOf(b)!=-1||g==b)return K(f,d)})};U.e=function(a,b,c,e){if(!b&&b!=\"\")throw Error(\"No link text specified\");a=L(a);var f=c||a;c=(new M(a)).d(\"A\");return n(c,function(d){var g=la(d);if(e&&g.indexOf(b)!=-1||g==b)return K(f,d)})};U.a=function(a,b,c){return U.f(a,b,c,false)};U.b=function(a,b,c){return U.e(a,b,c,false)};",
L"V.a=function(a,b,c){return U.f(a,b,c,true)};V.b=function(a,b,c){return U.e(a,b,c,true)};var W={};W.c=function(a,b,c,e){if(Q(b,\"name\")==a)return c==e||K(c,b);return false};W.a=function(a,b,c){var e=L(a),f=c||e;if(e.getElementsByName){a=e.getElementsByName(b);c=a.length;for(var d=0;d<c;d++)if(a[d].getAttribute(\"name\")===b)if(!(f!=e&&!K(f,a[d])))return a[d]}a=e.getElementsByTagName(\"*\");return o(a,function(g){return W.c(b,g,f,e)})};W.b=function(a,b,c){var e=L(a),f=c||e;a=e.getElementsByTagName(\"*\");return n(a,function(d){return W.c(b,d,f,e)})};var X={};X.a=function(a,b,c){a=L(a);c=c||a;if(!j(a.evaluate))throw Error(\"XPath location is not supported\");if(!b)throw Error(\"No xpath specified\");return(b=a.evaluate(b,c,null,9,null).singleNodeValue)?b:null};X.b=function(a,b,c){a=L(a);c=c||a;if(!j(a.evaluate))throw Error(\"XPath location is not supported\");if(!b)throw Error(\"No xpath specified\");b=a.evaluate(b,c,null,5,null);c=[];for(a=b.iterateNext();a;){c.push(a);a=b.iterateNext()}return c};var ma={className:N,css:O,id:T,link:U,name:W,partialLink:V,xpath:X};var na=function(a,b){a:{var c;b:{for(c in a){c=c;break b}c=void 0}if(c){var e=ma[c];if(e&&j(e.a)){a=ba(e.a,null,h,a[c],b);break a}}throw new Error(\"Unsupported locator strategy: \"+c);}return a()},Y=\"findElement\".split(\".\"),Z=h;!(Y[0]in Z)&&Z.execScript&&Z.execScript(\"var \"+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&na!==undefined)Z[$]=na;else Z=Z[$]?Z[$]:(Z[$]={});",
NULL
};

#endif

/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef FIND_ELEMENTS_H
#define FIND_ELEMENTS_H

wchar_t* FIND_ELEMENTS[] = {
L"var h=this;",
L"function aa(a){var b=typeof a;if(b==\"object\")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)==\"[object Array]\"||typeof a.length==\"number\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)==\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\")))return\"function\"}else return\"null\";else if(b==",
L"\"function\"&&typeof a.call==\"undefined\")return\"object\";return b}function i(a){return typeof a==\"string\"}function j(a){return aa(a)==\"function\"}function ba(a,b){var c=b||h;if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,e);return a.apply(c,f)}}else return function(){return a.apply(c,arguments)}};var k=Array.prototype,l=k.indexOf?function(a,b,c){return k.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(i(a)){if(!i(b)||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},n=k.filter?function(a,b,c){return k.filter.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=[],d=0,g=i(a)?a.split(\"\"):a,m=0;m<e;m++)if(m in g){var A=g[m];if(b.call(c,A,m,a))f[d++]=A}return f};",
L"function o(a,b,c){a:{for(var e=a.length,f=i(a)?a.split(\"\"):a,d=0;d<e;d++)if(d in f&&b.call(c,f[d],d,a)){b=d;break a}b=-1}return b<0?null:i(a)?a.charAt(b):a[b]};function p(a,b){this.width=a;this.height=b}p.prototype.toString=function(){return\"(\"+this.width+\" x \"+this.height+\")\"};function q(a){return a.replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}",
L"function r(a,b){var c=0;a=q(String(a)).split(\".\");b=q(String(b)).split(\".\");for(var e=Math.max(a.length,b.length),f=0;c==0&&f<e;f++){var d=a[f]||\"\",g=b[f]||\"\",m=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),A=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var u=m.exec(d)||[\"\",\"\",\"\"],v=A.exec(g)||[\"\",\"\",\"\"];if(u[0].length==0&&v[0].length==0)break;c=s(u[1].length==0?0:parseInt(u[1],10),v[1].length==0?0:parseInt(v[1],10))||s(u[2].length==0,v[2].length==0)||s(u[2],v[2])}while(c==0)}return c}",
L"function s(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var t,w,x,y;function z(){return h.navigator?h.navigator.userAgent:null}y=x=w=t=false;var B;if(B=z()){var ca=h.navigator;t=B.indexOf(\"Opera\")==0;w=!t&&B.indexOf(\"MSIE\")!=-1;x=!t&&B.indexOf(\"WebKit\")!=-1;y=!t&&!x&&ca.product==\"Gecko\"}var C=t,da=w,ea=y,D=x,E,F=\"\",G;if(C&&h.opera){var H=h.opera.version;F=typeof H==\"function\"?H():H}else{if(ea)G=/rv\\:([^\\);]+)(\\)|;)/;else if(da)G=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(D)G=/WebKit\\/(\\S+)/;if(G){var I=G.exec(z());F=I?I[1]:\"\"}}E=F;var J={};function K(a,b){if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!=\"undefined\")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function L(a){return a.nodeType==9?a:a.ownerDocument||a.document}function M(a){this.g=a||h.document||document}",
L"M.prototype.d=function(a,b,c){var e=this.g;c=c||e;a=a&&a!=\"*\"?a.toUpperCase():\"\";if(c.querySelectorAll&&(a||b)&&(!D||e.compatMode==\"CSS1Compat\"||J[\"528\"]||(J[\"528\"]=r(E,\"528\")>=0)))b=c.querySelectorAll(a+(b?\".\"+b:\"\"));else if(b&&c.getElementsByClassName){e=c.getElementsByClassName(b);if(a){c={};for(var f=0,d=0,g;g=e[d];d++)if(a==g.nodeName)c[f++]=g;c.length=f;b=c}else b=e}else{e=c.getElementsByTagName(a||\"*\");if(b){c={};for(d=f=0;g=e[d];d++){a=g.className;if(typeof a.split==\"function\"&&l(a.split(/\\s+/),",
L"b)>=0)c[f++]=g}c.length=f;b=c}else b=e}return b};M.prototype.contains=K;var N={};N.c=function(a,b,c){return b==c||K(b,a)};N.b=function(a,b,c){if(!b)throw Error(\"No class name specified\");b=q(b);if(b.split(/\\s+/).length>1)throw Error(\"Compound class names not permitted\");var e=L(a),f=c||e;a=(new M(e)).d(\"*\",b);return o(a,function(d){return N.c(d,f,e)})};",
L"N.a=function(a,b,c){if(!b)throw Error(\"No class name specified\");b=q(b);if(b.split(/\\s+/).length>1)throw Error(\"Compound class names not permitted\");var e=L(a),f=c||e;a=(new M(e)).d(\"*\",b);return n(a,function(d){return N.c(d,f,e)})};var O={};O.b=function(a,b,c){a=c||L(a);if(!j(a.querySelector))throw Error(\"CSS selection is not supported\");if(!b)throw Error(\"No selector specified\");if(b.split(/,/).length>1)throw Error(\"Compound selectors not permitted\");b=q(b);return(b=a.querySelector(b))?b:null};O.a=function(a,b,c){a=c||L(a);if(!j(a.querySelectorAll))throw Error(\"CSS selection is not supported\");if(!b)throw Error(\"No selector specified\");if(b.split(/,/).length>1)throw Error(\"Compound selectors not permitted\");b=q(b);return a.querySelectorAll(b)};function P(a,b){var c=L(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(a=c.defaultView.getComputedStyle(a,\"\"))return a[b];return null}",
L"function fa(a){var b=C&&!(J[\"10\"]||(J[\"10\"]=r(E,\"10\")>=0));if((P(a,\"display\")||(a.currentStyle?a.currentStyle.display:null)||a.style.display)!=\"none\")return b?new p(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new p(a.offsetWidth,a.offsetHeight);var c=a.style,e=c.display,f=c.visibility,d=c.position;c.visibility=\"hidden\";c.position=\"absolute\";c.display=\"inline\";if(b){b=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{b=a.offsetWidth;a=a.offsetHeight}c.display=e;c.position=",
L"d;c.visibility=f;return new p(b,a)};function ga(a,b){if(j(a.hasAttribute))if(a.hasAttribute(b))return true;return a[b]!==undefined}var ha=[\"async\",\"autofocus\",\"autoplay\",\"checked\",\"compact\",\"complete\",\"declare\",\"defaultChecked\",\"defaultSelected\",\"defer\",\"disabled\",\"draggable\",\"ended\",\"formNoValidate\",\"hidden\",\"indeterminate\",\"isContentEditable\",\"isMap\",\"loop\",\"multiple\",\"muted\",\"noHref\",\"noResize\",\"noShade\",\"noWrap\",\"noValidate\",\"open\",\"paused\",\"readOnly\",\"required\",\"reversed\",\"scoped\",\"seamless\",\"seeking\",\"selected\",\"visible\",\"willValidate\"];",
L"function Q(a,b){if(!a)throw Error(\"Element has not been specified\");if(!b)throw Error(\"Attribute name must be set\");var c=b.toLowerCase();if(l(ha,b)>=0){if(!ga(a,b))return false;a=a[b];return!!(a&&a!=\"false\")}if(!ga(a,b))return null;if(\"style\"==c){a=a.style;return a.cssText?a.cssText:\"\"}if(\"class\"==c)b=\"className\";if(\"readonly\"==c)b=\"readOnly\";return a[b]===undefined?a.getAttribute(b):a[b]}",
L"function ia(a){if(!a||!a.parentNode)return null;for(a=a.parentNode;a.nodeType!=1&&!(a.nodeType==9||a.nodeType==11);)a=a.parentNode;return a&&a.nodeType==1?a:null}",
L"function ja(a){if(!a)throw new Error(\"No value given for isDisplayed required parameter.\");var b=a;if(b.nodeType!=1)b=ia(a);if(!b)throw new Error(\"Node given does not have a parent element.\");var c=L(b)?L(b).parentWindow||L(b).defaultView:window;function e(d,g){if(c.getComputedStyle)return P(d,g);return d.currentStyle?d.currentStyle[g]:null}function f(d){if(e(d,\"display\")==\"none\")return false;d=ia(d);return!d||f(d)}if(!((b.tagName.toLowerCase()==\"input\"&&b.type.toLowerCase()==\"hidden\"?false:e(b,\"visibility\")!=",
L"\"hidden\")&&f(b)))return false;a=fa(b);return a.height>0&&a.width>0}",
L"function R(a,b,c){if(a.tagName&&a.tagName==\"SCRIPT\")return[b,c];else if(a.tagName&&a.tagName==\"TITLE\")return[c+a.text,\"\"];for(var e=a.childNodes,f=0;f<e.length;f++){var d=e[f];if(d.tagName&&d.tagName==\"PRE\"){b+=S(c);c=\"\";d=R(d,b,\"\",true);b+=d[1]}else if(d.nodeName==\"#text\"){if(ja(d)){d=d.nodeValue;d=d.replace(new RegExp(String.fromCharCode(160),\"gm\"),\" \");c+=d}}else{d=R(d,b,c,false);b=d[0];c=d[1]}}if(a.tagName&&a.tagName==\"BR\"?true:false)if(a.tagName&&a.tagName!=\"PRE\"){b+=S(c)+\"\\n\";c=\"\"}else b+=\"\\n\";",
L"return[b,c]}function S(a){return a.replace(/[\\s\\xa0]+/g,\" \")}function ka(a){return a==\"\\n\"||a==\" \"||a==\"\\t\"||a==\"\\r\"||a==\"\\u00a0\"}function la(a){a=R(a,\"\",\"\",a.tagName==\"PRE\");a=a[0]+S(a[1]);for(var b=0;b<a.length&&ka(a[b]);)++b;for(var c=a.length;c>b&&ka(a[c-1]);)--c;return a.slice(b,c)};var T={};T.b=function(a,b,c){a=L(a);c=c||a;var e=a.getElementById(b);if(!e)return null;if(e.getAttribute(\"id\")==b&&K(c,e))return e;a=a.getElementsByTagName(\"*\");e=a.length;for(var f=0;f<e;f++){var d=a[f];if(d.tagName.toLowerCase()==\"form\"){if(d.attributes.id.nodeValue==b&&K(c,d))return d}else if(Q(d,\"id\")==b&&K(c,d))return d}return null};T.a=function(a,b,c){a=L(a);var e=c||a;c=a.getElementsByTagName(\"*\");return n(c,function(f){return Q(f,\"id\")==b&&K(e,f)})};var U={},V={};U.f=function(a,b,c,e){if(!b&&b!=\"\")throw Error(\"No link text specified\");a=L(a);var f=c||a;c=(new M(a)).d(\"A\");return o(c,function(d){var g=la(d);if(e&&g.indexOf(b)!=-1||g==b)return K(f,d)})};U.e=function(a,b,c,e){if(!b&&b!=\"\")throw Error(\"No link text specified\");a=L(a);var f=c||a;c=(new M(a)).d(\"A\");return n(c,function(d){var g=la(d);if(e&&g.indexOf(b)!=-1||g==b)return K(f,d)})};U.b=function(a,b,c){return U.f(a,b,c,false)};U.a=function(a,b,c){return U.e(a,b,c,false)};",
L"V.b=function(a,b,c){return U.f(a,b,c,true)};V.a=function(a,b,c){return U.e(a,b,c,true)};var W={};W.c=function(a,b,c,e){if(Q(b,\"name\")==a)return c==e||K(c,b);return false};W.b=function(a,b,c){var e=L(a),f=c||e;if(e.getElementsByName){a=e.getElementsByName(b);c=a.length;for(var d=0;d<c;d++)if(a[d].getAttribute(\"name\")===b)if(!(f!=e&&!K(f,a[d])))return a[d]}a=e.getElementsByTagName(\"*\");return o(a,function(g){return W.c(b,g,f,e)})};W.a=function(a,b,c){var e=L(a),f=c||e;a=e.getElementsByTagName(\"*\");return n(a,function(d){return W.c(b,d,f,e)})};var X={};X.b=function(a,b,c){a=L(a);c=c||a;if(!j(a.evaluate))throw Error(\"XPath location is not supported\");if(!b)throw Error(\"No xpath specified\");return(b=a.evaluate(b,c,null,9,null).singleNodeValue)?b:null};X.a=function(a,b,c){a=L(a);c=c||a;if(!j(a.evaluate))throw Error(\"XPath location is not supported\");if(!b)throw Error(\"No xpath specified\");b=a.evaluate(b,c,null,5,null);c=[];for(a=b.iterateNext();a;){c.push(a);a=b.iterateNext()}return c};var ma={className:N,css:O,id:T,link:U,name:W,partialLink:V,xpath:X};var na=function(a,b){a:{var c;b:{for(c in a){c=c;break b}c=void 0}if(c){var e=ma[c];if(e&&j(e.a)){a=ba(ma[c].a,null,h,a[c],b);break a}}throw new Error(\"Unsupported locator strategy: \"+c);}return a()},Y=\"findElements\".split(\".\"),Z=h;!(Y[0]in Z)&&Z.execScript&&Z.execScript(\"var \"+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&na!==undefined)Z[$]=na;else Z=Z[$]?Z[$]:(Z[$]={});",
NULL
};

#endif

/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef GET_ATTRIBUTE_H
#define GET_ATTRIBUTE_H

wchar_t* GET_ATTRIBUTE[] = {
L"var d=this;",
L"function e(a){var b=typeof a;if(b==\"object\")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)==\"[object Array]\"||typeof a.length==\"number\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)==\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\")))return\"function\"}else return\"null\";else if(b==",
L"\"function\"&&typeof a.call==\"undefined\")return\"object\";return b};var f=Array.prototype,g=f.indexOf?function(a,b,c){return f.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(typeof a==\"string\"){if(typeof b!=\"string\"||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var h,i,j,k;function l(){return d.navigator?d.navigator.userAgent:null}k=j=i=h=false;var m;if(m=l()){var n=d.navigator;h=m.indexOf(\"Opera\")==0;i=!h&&m.indexOf(\"MSIE\")!=-1;j=!h&&m.indexOf(\"WebKit\")!=-1;k=!h&&!j&&n.product==\"Gecko\"}var o=i,p=k,q=j,r=\"\",s;if(h&&d.opera){var t=d.opera.version;r=typeof t==\"function\"?t():t}else{if(p)s=/rv\\:([^\\);]+)(\\)|;)/;else if(o)s=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(q)s=/WebKit\\/(\\S+)/;if(s){var u=s.exec(l());r=u?u[1]:\"\"}};function v(a,b){if(e(a.hasAttribute)==\"function\")if(a.hasAttribute(b))return true;return a[b]!==undefined}",
L"var w=[\"async\",\"autofocus\",\"autoplay\",\"checked\",\"compact\",\"complete\",\"declare\",\"defaultChecked\",\"defaultSelected\",\"defer\",\"disabled\",\"draggable\",\"ended\",\"formNoValidate\",\"hidden\",\"indeterminate\",\"isContentEditable\",\"isMap\",\"loop\",\"multiple\",\"muted\",\"noHref\",\"noResize\",\"noShade\",\"noWrap\",\"noValidate\",\"open\",\"paused\",\"readOnly\",\"required\",\"reversed\",\"scoped\",\"seamless\",\"seeking\",\"selected\",\"visible\",\"willValidate\"];var x=function(a,b){if(!a)throw Error(\"Element has not been specified\");if(!b)throw Error(\"Attribute name must be set\");var c=b.toLowerCase();if(g(w,b)>=0){if(!v(a,b))return false;a=a[b];return!!(a&&a!=\"false\")}if(!v(a,b))return null;if(\"style\"==c){a=a.style;return a.cssText?a.cssText:\"\"}if(\"class\"==c)b=\"className\";if(\"readonly\"==c)b=\"readOnly\";return a[b]===undefined?a.getAttribute(b):a[b]},y=\"getAttribute\".split(\".\"),z=d;!(y[0]in z)&&z.execScript&&z.execScript(\"var \"+y[0]);",
L"for(var A;y.length&&(A=y.shift());)if(!y.length&&x!==undefined)z[A]=x;else z=z[A]?z[A]:(z[A]={});",
NULL
};

#endif

/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef GET_LOCATION_H
#define GET_LOCATION_H

wchar_t* GET_LOCATION[] = {
L"var e=this;var f;function g(a,b){this.x=a!==undefined?a:0;this.y=b!==undefined?b:0}g.prototype.toString=function(){return\"(\"+this.x+\", \"+this.y+\")\"};var h,j,k,l;function m(){return e.navigator?e.navigator.userAgent:null}l=k=j=h=false;var n;if(n=m()){var o=e.navigator;h=n.indexOf(\"Opera\")==0;j=!h&&n.indexOf(\"MSIE\")!=-1;k=!h&&n.indexOf(\"WebKit\")!=-1;l=!h&&!k&&o.product==\"Gecko\"}var p=h,q=j,r=l,s=k,u=\"\",v;if(p&&e.opera){var w=e.opera.version;u=typeof w==\"function\"?w():w}else{if(r)v=/rv\\:([^\\);]+)(\\)|;)/;else if(q)v=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(s)v=/WebKit\\/(\\S+)/;if(v){var x=v.exec(m());u=x?x[1]:\"\"}};function y(a){return a.nodeType==9?a:a.ownerDocument||a.document}function z(a){this.a=a||e.document||document}function A(a){return a.a.compatMode==\"CSS1Compat\"};function B(a,b){var c;a:{c=y(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaultView.getComputedStyle(a,\"\")){c=c[b];break a}c=null}return c||(a.currentStyle?a.currentStyle[b]:null)||a.style[b]}",
L"function C(a){if(q)return a.offsetParent;var b=y(a),c=B(a,\"position\"),i=c==\"fixed\"||c==\"absolute\";for(a=a.parentNode;a&&a!=b;a=a.parentNode){c=B(a,\"position\");i=i&&c==\"static\"&&a!=b.documentElement&&a!=b.body;if(!i&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||c==\"fixed\"||c==\"absolute\"))return a}return null};var D=function(a){var b,c=y(a),i=B(a,\"position\"),H=r&&c.getBoxObjectFor&&!a.getBoundingClientRect&&i==\"absolute\"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),d=new g(0,0),t;b=c?c.nodeType==9?c:y(c):document;t=q&&!A(b?new z(y(b)):f||(f=new z))?b.body:b.documentElement;if(a==t)return d;if(a.getBoundingClientRect){b=a.getBoundingClientRect();if(q){a=a.ownerDocument;b.left-=a.documentElement.clientLeft+a.body.clientLeft;b.top-=a.documentElement.clientTop+a.body.clientTop}b=b;c=(c?new z(y(c)):",
L"f||(f=new z)).a;c=!s&&c.compatMode==\"CSS1Compat\"?c.documentElement:c.body;c=new g(c.scrollLeft,c.scrollTop);d.x=b.left+c.x;d.y=b.top+c.y}else if(c.getBoxObjectFor&&!H){b=c.getBoxObjectFor(a);c=c.getBoxObjectFor(t);d.x=b.screenX-c.screenX;d.y=b.screenY-c.screenY}else{b=a;do{d.x+=b.offsetLeft;d.y+=b.offsetTop;if(b!=a){d.x+=b.clientLeft||0;d.y+=b.clientTop||0}if(s&&B(b,\"position\")==\"fixed\"){d.x+=c.body.scrollLeft;d.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(p||s&&i==\"absolute\")d.y-=",
L"c.body.offsetTop;for(b=a;(b=C(b))&&b!=c.body&&b!=t;){d.x-=b.scrollLeft;if(!p||b.tagName!=\"TR\")d.y-=b.scrollTop}}return d},E=\"getLocation\".split(\".\"),F=e;!(E[0]in F)&&F.execScript&&F.execScript(\"var \"+E[0]);for(var G;E.length&&(G=E.shift());)if(!E.length&&D!==undefined)F[G]=D;else F=F[G]?F[G]:(F[G]={});",
NULL
};

#endif

/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef GET_SIZE_H
#define GET_SIZE_H

wchar_t* GET_SIZE[] = {
L"var d=this;function e(a,c){this.width=a;this.height=c}e.prototype.toString=function(){return\"(\"+this.width+\" x \"+this.height+\")\"};function g(a,c){var b=0;a=String(a).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");c=String(c).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");for(var p=Math.max(a.length,c.length),f=0;b==0&&f<p;f++){var q=a[f]||\"\",D=c[f]||\"\",E=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),F=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var h=E.exec(q)||[\"\",\"\",\"\"],i=F.exec(D)||[\"\",\"\",\"\"];if(h[0].length==0&&i[0].length==0)break;b=j(h[1].length==0?0:parseInt(h[1],10),i[1].length==0?0:parseInt(i[1],10))||j(h[2].length==0,i[2].length==0)||j(h[2],",
L"i[2])}while(b==0)}return b}function j(a,c){if(a<c)return-1;else if(a>c)return 1;return 0};var k,l,m,n;function o(){return d.navigator?d.navigator.userAgent:null}n=m=l=k=false;var r;if(r=o()){var s=d.navigator;k=r.indexOf(\"Opera\")==0;l=!k&&r.indexOf(\"MSIE\")!=-1;m=!k&&r.indexOf(\"WebKit\")!=-1;n=!k&&!m&&s.product==\"Gecko\"}var t=k,u=l,v=n,w=m,x,y=\"\",z;if(t&&d.opera){var A=d.opera.version;y=typeof A==\"function\"?A():A}else{if(v)z=/rv\\:([^\\);]+)(\\)|;)/;else if(u)z=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(w)z=/WebKit\\/(\\S+)/;if(z){var B=z.exec(o());y=B?B[1]:\"\"}}x=y;var C={};var G=function(a){var c=t&&!(C[\"10\"]||(C[\"10\"]=g(x,\"10\")>=0)),b;a:{b=a.nodeType==9?a:a.ownerDocument||a.document;if(b.defaultView&&b.defaultView.getComputedStyle)if(b=b.defaultView.getComputedStyle(a,\"\")){b=b.display;break a}b=null}if((b||(a.currentStyle?a.currentStyle.display:null)||a.style.display)!=\"none\")return c?new e(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new e(a.offsetWidth,a.offsetHeight);b=a.style;var p=b.display,f=b.visibility,q=b.position;b.visibility=\"hidden\";b.position=",
L"\"absolute\";b.display=\"inline\";if(c){c=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{c=a.offsetWidth;a=a.offsetHeight}b.display=p;b.position=q;b.visibility=f;return new e(c,a)},H=\"getSize\".split(\".\"),I=d;!(H[0]in I)&&I.execScript&&I.execScript(\"var \"+H[0]);for(var J;H.length&&(J=H.shift());)if(!H.length&&G!==undefined)I[J]=G;else I=I[J]?I[J]:(I[J]={});",
NULL
};

#endif

/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef GET_VISIBLE_TEXT_H
#define GET_VISIBLE_TEXT_H

wchar_t* GET_VISIBLE_TEXT[] = {
L"var g=this;function h(a,b){this.width=a;this.height=b}h.prototype.toString=function(){return\"(\"+this.width+\" x \"+this.height+\")\"};function i(a,b){var c=0;a=String(a).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");b=String(b).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");for(var f=Math.max(a.length,b.length),e=0;c==0&&e<f;e++){var d=a[e]||\"\",p=b[e]||\"\",J=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),K=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var j=J.exec(d)||[\"\",\"\",\"\"],k=K.exec(p)||[\"\",\"\",\"\"];if(j[0].length==0&&k[0].length==0)break;c=l(j[1].length==0?0:parseInt(j[1],10),k[1].length==0?0:parseInt(k[1],10))||l(j[2].length==0,k[2].length==0)||l(j[2],",
L"k[2])}while(c==0)}return c}function l(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var m,n,o,q;function r(){return g.navigator?g.navigator.userAgent:null}q=o=n=m=false;var s;if(s=r()){var t=g.navigator;m=s.indexOf(\"Opera\")==0;n=!m&&s.indexOf(\"MSIE\")!=-1;o=!m&&s.indexOf(\"WebKit\")!=-1;q=!m&&!o&&t.product==\"Gecko\"}var u=m,v=n,w=q,x=o,y,z=\"\",A;if(u&&g.opera){var B=g.opera.version;z=typeof B==\"function\"?B():B}else{if(w)A=/rv\\:([^\\);]+)(\\)|;)/;else if(v)A=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(x)A=/WebKit\\/(\\S+)/;if(A){var C=A.exec(r());z=C?C[1]:\"\"}}y=z;var D={};function E(a,b){var c=a.nodeType==9?a:a.ownerDocument||a.document;if(c.defaultView&&c.defaultView.getComputedStyle)if(a=c.defaultView.getComputedStyle(a,\"\"))return a[b];return null}",
L"function F(a){var b=u&&!(D[\"10\"]||(D[\"10\"]=i(y,\"10\")>=0));if((E(a,\"display\")||(a.currentStyle?a.currentStyle.display:null)||a.style.display)!=\"none\")return b?new h(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new h(a.offsetWidth,a.offsetHeight);var c=a.style,f=c.display,e=c.visibility,d=c.position;c.visibility=\"hidden\";c.position=\"absolute\";c.display=\"inline\";if(b){b=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{b=a.offsetWidth;a=a.offsetHeight}c.display=f;c.position=",
L"d;c.visibility=e;return new h(b,a)};function G(a){if(!a||!a.parentNode)return null;for(a=a.parentNode;a.nodeType!=1&&!(a.nodeType==9||a.nodeType==11);)a=a.parentNode;return a&&a.nodeType==1?a:null}",
L"function H(a){if(!a)throw new Error(\"No value given for isDisplayed required parameter.\");var b=a;if(b.nodeType!=1)b=G(a);if(!b)throw new Error(\"Node given does not have a parent element.\");var c=(b.nodeType==9?b:b.ownerDocument||b.document)?(b.nodeType==9?b:b.ownerDocument||b.document).parentWindow||(b.nodeType==9?b:b.ownerDocument||b.document).defaultView:window;function f(d,p){if(c.getComputedStyle)return E(d,p);return d.currentStyle?d.currentStyle[p]:null}function e(d){if(f(d,\"display\")==\"none\")return false;",
L"d=G(d);return!d||e(d)}if(!((b.tagName.toLowerCase()==\"input\"&&b.type.toLowerCase()==\"hidden\"?false:f(b,\"visibility\")!=\"hidden\")&&e(b)))return false;a=F(b);return a.height>0&&a.width>0}",
L"function I(a,b,c){if(a.tagName&&a.tagName==\"SCRIPT\")return[b,c];else if(a.tagName&&a.tagName==\"TITLE\")return[c+a.text,\"\"];for(var f=a.childNodes,e=0;e<f.length;e++){var d=f[e];if(d.tagName&&d.tagName==\"PRE\"){b+=L(c);c=\"\";d=I(d,b,\"\",true);b+=d[1]}else if(d.nodeName==\"#text\"){if(H(d)){d=d.nodeValue;d=d.replace(new RegExp(String.fromCharCode(160),\"gm\"),\" \");c+=d}}else{d=I(d,b,c,false);b=d[0];c=d[1]}}if(a.tagName&&a.tagName==\"BR\"?true:false)if(a.tagName&&a.tagName!=\"PRE\"){b+=L(c)+\"\\n\";c=\"\"}else b+=\"\\n\";",
L"return[b,c]}function L(a){return a.replace(/[\\s\\xa0]+/g,\" \")}function M(a){return a==\"\\n\"||a==\" \"||a==\"\\t\"||a==\"\\r\"||a==\"\\u00a0\"};var N=function(a){a=I(a,\"\",\"\",a.tagName==\"PRE\");a=a[0]+L(a[1]);for(var b=0;b<a.length&&M(a[b]);)++b;for(var c=a.length;c>b&&M(a[c-1]);)--c;return a.slice(b,c)},O=\"getVisibleText\".split(\".\"),P=g;!(O[0]in P)&&P.execScript&&P.execScript(\"var \"+O[0]);for(var Q;O.length&&(Q=O.shift());)if(!O.length&&N!==undefined)P[Q]=N;else P=P[Q]?P[Q]:(P[Q]={});",
NULL
};

#endif

/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef IS_DISPLAYED_H
#define IS_DISPLAYED_H

wchar_t* IS_DISPLAYED[] = {
L"var f=this;function g(a,b){this.width=a;this.height=b}g.prototype.toString=function(){return\"(\"+this.width+\" x \"+this.height+\")\"};function i(a,b){var c=0;a=String(a).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");b=String(b).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");for(var h=Math.max(a.length,b.length),e=0;c==0&&e<h;e++){var d=a[e]||\"\",p=b[e]||\"\",G=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),H=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var j=G.exec(d)||[\"\",\"\",\"\"],k=H.exec(p)||[\"\",\"\",\"\"];if(j[0].length==0&&k[0].length==0)break;c=l(j[1].length==0?0:parseInt(j[1],10),k[1].length==0?0:parseInt(k[1],10))||l(j[2].length==0,k[2].length==0)||l(j[2],",
L"k[2])}while(c==0)}return c}function l(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var m,n,o,q;function r(){return f.navigator?f.navigator.userAgent:null}q=o=n=m=false;var s;if(s=r()){var t=f.navigator;m=s.indexOf(\"Opera\")==0;n=!m&&s.indexOf(\"MSIE\")!=-1;o=!m&&s.indexOf(\"WebKit\")!=-1;q=!m&&!o&&t.product==\"Gecko\"}var u=m,v=n,w=q,x=o,y,z=\"\",A;if(u&&f.opera){var B=f.opera.version;z=typeof B==\"function\"?B():B}else{if(w)A=/rv\\:([^\\);]+)(\\)|;)/;else if(v)A=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(x)A=/WebKit\\/(\\S+)/;if(A){var C=A.exec(r());z=C?C[1]:\"\"}}y=z;var D={};function E(a,b){var c=a.nodeType==9?a:a.ownerDocument||a.document;if(c.defaultView&&c.defaultView.getComputedStyle)if(a=c.defaultView.getComputedStyle(a,\"\"))return a[b];return null}",
L"function F(a){var b=u&&!(D[\"10\"]||(D[\"10\"]=i(y,\"10\")>=0));if((E(a,\"display\")||(a.currentStyle?a.currentStyle.display:null)||a.style.display)!=\"none\")return b?new g(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new g(a.offsetWidth,a.offsetHeight);var c=a.style,h=c.display,e=c.visibility,d=c.position;c.visibility=\"hidden\";c.position=\"absolute\";c.display=\"inline\";if(b){b=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{b=a.offsetWidth;a=a.offsetHeight}c.display=h;c.position=",
L"d;c.visibility=e;return new g(b,a)};function I(a){if(!a||!a.parentNode)return null;for(a=a.parentNode;a.nodeType!=1&&!(a.nodeType==9||a.nodeType==11);)a=a.parentNode;return a&&a.nodeType==1?a:null};var J=function(a){if(!a)throw new Error(\"No value given for isDisplayed required parameter.\");var b=a;if(b.nodeType!=1)b=I(a);if(!b)throw new Error(\"Node given does not have a parent element.\");var c=(b.nodeType==9?b:b.ownerDocument||b.document)?(b.nodeType==9?b:b.ownerDocument||b.document).parentWindow||(b.nodeType==9?b:b.ownerDocument||b.document).defaultView:window;function h(d,p){if(c.getComputedStyle)return E(d,p);return d.currentStyle?d.currentStyle[p]:null}function e(d){if(h(d,\"display\")==",
L"\"none\")return false;d=I(d);return!d||e(d)}if(!((b.tagName.toLowerCase()==\"input\"&&b.type.toLowerCase()==\"hidden\"?false:h(b,\"visibility\")!=\"hidden\")&&e(b)))return false;a=F(b);return a.height>0&&a.width>0},K=\"isDisplayed\".split(\".\"),L=f;!(K[0]in L)&&L.execScript&&L.execScript(\"var \"+K[0]);for(var M;K.length&&(M=K.shift());)if(!K.length&&J!==undefined)L[M]=J;else L=L[M]?L[M]:(L[M]={});",
NULL
};

#endif

/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef IS_SELECTED_H
#define IS_SELECTED_H

wchar_t* IS_SELECTED[] = {
L"var d=this;",
L"function e(a){var b=typeof a;if(b==\"object\")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)==\"[object Array]\"||typeof a.length==\"number\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)==\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\")))return\"function\"}else return\"null\";else if(b==",
L"\"function\"&&typeof a.call==\"undefined\")return\"object\";return b};var f=Array.prototype,g=f.indexOf?function(a,b,c){return f.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(typeof a==\"string\"){if(typeof b!=\"string\"||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var h,i,j,k;function l(){return d.navigator?d.navigator.userAgent:null}k=j=i=h=false;var m;if(m=l()){var n=d.navigator;h=m.indexOf(\"Opera\")==0;i=!h&&m.indexOf(\"MSIE\")!=-1;j=!h&&m.indexOf(\"WebKit\")!=-1;k=!h&&!j&&n.product==\"Gecko\"}var o=i,p=k,q=j,r=\"\",s;if(h&&d.opera){var t=d.opera.version;r=typeof t==\"function\"?t():t}else{if(p)s=/rv\\:([^\\);]+)(\\)|;)/;else if(o)s=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(q)s=/WebKit\\/(\\S+)/;if(s){var u=s.exec(l());r=u?u[1]:\"\"}};function v(a,b){if(e(a.hasAttribute)==\"function\")if(a.hasAttribute(b))return true;return a[b]!==undefined}",
L"var w=[\"async\",\"autofocus\",\"autoplay\",\"checked\",\"compact\",\"complete\",\"declare\",\"defaultChecked\",\"defaultSelected\",\"defer\",\"disabled\",\"draggable\",\"ended\",\"formNoValidate\",\"hidden\",\"indeterminate\",\"isContentEditable\",\"isMap\",\"loop\",\"multiple\",\"muted\",\"noHref\",\"noResize\",\"noShade\",\"noWrap\",\"noValidate\",\"open\",\"paused\",\"readOnly\",\"required\",\"reversed\",\"scoped\",\"seamless\",\"seeking\",\"selected\",\"visible\",\"willValidate\"];",
L"function x(a,b){if(!a)throw Error(\"Element has not been specified\");if(!b)throw Error(\"Attribute name must be set\");var c=b.toLowerCase();if(g(w,b)>=0){if(!v(a,b))return false;a=a[b];return!!(a&&a!=\"false\")}if(!v(a,b))return null;if(\"style\"==c){a=a.style;return a.cssText?a.cssText:\"\"}if(\"class\"==c)b=\"className\";if(\"readonly\"==c)b=\"readOnly\";return a[b]===undefined?a.getAttribute(b):a[b]};var y=function(a){if(v(a,\"checked\"))return x(a,\"checked\");if(v(a,\"selected\"))return x(a,\"selected\");throw Error(\"Element has neither checked nor selected attributes\");},z=\"isSelected\".split(\".\"),A=d;!(z[0]in A)&&A.execScript&&A.execScript(\"var \"+z[0]);for(var B;z.length&&(B=z.shift());)if(!z.length&&y!==undefined)A[B]=y;else A=A[B]?A[B]:(A[B]={});",
NULL
};

#endif

