// Copyright (c) Google Inc. 2009
// All rights reserved.
// This file is automatically generated by GRIT. Do not edit.
// Built on Wed Feb 25 12:02:09 2009

#pragma once

#define IDR_NET_ERROR_HTML 29447
#define IDR_INSECURE_CONTENT_STAMP 29448
#define IDR_ERROR_NO_DETAILS_HTML 29449
#define IDR_GREASEMONKEY_API_JS 29450
