/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef FINDELEMENTS_H
#define FINDELEMENTS_H

wchar_t* FINDELEMENTS[] = {
L"var h=this;",
L"function i(a){var b=typeof a;if(b==\"object\")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)==\"[object Array]\"||typeof a.length==\"number\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)==\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\")))return\"function\"}else return\"null\";else if(b==",
L"\"function\"&&typeof a.call==\"undefined\")return\"object\";return b}function j(a){return i(a)==\"function\"}function k(a,b){var c=b||h;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}};var m=Array.prototype,n=m.indexOf?function(a,b,c){return m.indexOf.call(a,b,c)}:function(a,b,c){for(c=c==null?0:c<0?Math.max(0,a.length+c):c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},o=m.filter?function(a,b,c){return m.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=typeof a==\"string\"?a.split(\"\"):a,l=0;l<d;l++)if(l in g){var x=g[l];if(b.call(c,x,l,a))e[f++]=x}return e};",
L"function p(a,b,c){a:{for(var d=a.length,e=typeof a==\"string\"?a.split(\"\"):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a)){b=f;break a}b=-1}return b<0?null:typeof a==\"string\"?a.charAt(b):a[b]};function q(a){return a.replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}",
L"function t(a,b){var c=0;a=q(String(a)).split(\".\");b=q(String(b)).split(\".\");for(var d=Math.max(a.length,b.length),e=0;c==0&&e<d;e++){var f=a[e]||\"\",g=b[e]||\"\",l=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),x=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var r=l.exec(f)||[\"\",\"\",\"\"],s=x.exec(g)||[\"\",\"\",\"\"];if(r[0].length==0&&s[0].length==0)break;c=u(r[1].length==0?0:parseInt(r[1],10),s[1].length==0?0:parseInt(s[1],10))||u(r[2].length==0,s[2].length==0)||u(r[2],s[2])}while(c==0)}return c}",
L"function u(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}(Date.now||function(){return+new Date})();var v,w,y,z;function A(){return h.navigator?h.navigator.userAgent:null}z=y=w=v=false;var B;if(B=A()){var C=h.navigator;v=B.indexOf(\"Opera\")==0;w=!v&&B.indexOf(\"MSIE\")!=-1;y=!v&&B.indexOf(\"WebKit\")!=-1;z=!v&&!y&&C.product==\"Gecko\"}var D=w,E=z,F=y,G,H=\"\",I;if(v&&h.opera){var J=h.opera.version;H=typeof J==\"function\"?J():J}else{if(E)I=/rv\\:([^\\);]+)(\\)|;)/;else if(D)I=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(F)I=/WebKit\\/(\\S+)/;if(I){var K=I.exec(A());H=K?K[1]:\"\"}}G=H;var L={};var M=F&&(L[\"522\"]||(L[\"522\"]=t(G,\"522\")>=0));function N(a,b){if(typeof a.contains!=\"undefined\"&&!M&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!=\"undefined\")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function O(a){return a.nodeType==9?a:a.ownerDocument||a.document}function P(a){this.e=a||h.document||document}",
L"P.prototype.d=function(a,b,c){var d=this.e;c=c||d;a=a&&a!=\"*\"?a.toLowerCase():\"\";if(c.querySelectorAll&&(a||b)&&(!F||d.compatMode==\"CSS1Compat\"||L[\"528\"]||(L[\"528\"]=t(G,\"528\")>=0)))b=c.querySelectorAll(a+(b?\".\"+b:\"\"));else if(b&&c.getElementsByClassName){d=c.getElementsByClassName(b);if(a){c={};for(var e=0,f=0,g;g=d[f];f++)if(a==g.nodeName.toLowerCase())c[e++]=g;c.length=e;b=c}else b=d}else{d=c.getElementsByTagName(a||\"*\");if(b){c={};for(f=e=0;g=d[f];f++){a=g.className;if(typeof a.split==\"function\"&&",
L"n(a.split(\" \"),b)>=0)c[e++]=g}c.length=e;b=c}else b=d}return b};P.prototype.contains=N;var Q={};Q.b=function(a,b,c){return b==c||N(b,a)};Q.c=function(a,b,c){if(!b)throw Error(\"No class name specified\");b=q(b);if(b.split(/\\s+/).length>1)throw Error(\"Compound class names not permitted\");var d=O(a),e=c||d;a=(new P(d)).d(\"*\",b);return p(a,function(f){return Q.b(f,e,d)})};",
L"Q.a=function(a,b,c){if(!b)throw Error(\"No class name specified\");b=q(b);if(b.split(/\\s+/).length>1)throw Error(\"Compound class names not permitted\");var d=O(a),e=c||d;a=(new P(d)).d(\"*\",b);return o(a,function(f){return Q.b(f,e,d)})};var R={};R.c=function(a,b,c){a=c||O(a);if(!j(a.querySelector))throw Error(\"CSS selection is not supported\");if(!b)throw Error(\"No selector specified\");if(b.split(/,/).length>1)throw Error(\"Compound selectors not permitted\");b=q(b);return(b=a.querySelector(b))?b:null};R.a=function(a,b,c){a=c||O(a);if(!j(a.querySelectorAll))throw Error(\"CSS selection is not supported\");if(!b)throw Error(\"No selector specified\");if(b.split(/,/).length>1)throw Error(\"Compound selectors not permitted\");b=q(b);return a.querySelectorAll(b)};function aa(a,b){if(j(a.hasAttribute))if(a.hasAttribute(b))return true;if(a[b]!==undefined)return true;for(var c in a)if(b==c)return true;return false}var ba=[\"checked\",\"disabled\",\"readOnly\",\"selected\"];",
L"function S(a,b){if(!a)throw Error(\"Element has not been specified\");if(!b)throw Error(\"Attribute name must be set\");var c=b.toLowerCase();if(n(ba,b)>=0){a=a[b];return!!(a&&a!=\"false\")}if(\"style\"==c){a=a.style;return a.cssText?a.cssText:\"\"}if(\"class\"==c)b=\"className\";if(\"readonly\"==c)b=\"readOnly\";if(!aa(a,b))return null;return a[b]===undefined?a.getAttribute(b):a[b]};var T={};T.c=function(a,b,c){a=O(a);c=c||a;var d=a.getElementById(b);if(!d)return null;if(d.getAttribute(\"id\")==b&&N(c,d))return d;a=a.getElementsByTagName(\"*\");d=a.length;for(var e=0;e<d;e++){var f=a[e];if(f.tagName.toLowerCase()==\"form\"){if(f.attributes.id.nodeValue==b&&N(c,f))return f}else if(S(f,\"id\")==b&&N(c,f))return f}return null};T.a=function(a,b,c){a=O(a);var d=c||a;c=a.getElementsByTagName(\"*\");return o(c,function(e){return S(e,\"id\")==b&&N(d,e)})};var U={};U.b=function(a,b,c,d){if(S(b,\"name\")==a)return c==d||N(c,b);return false};U.c=function(a,b,c){var d=O(a),e=c||d;if(d.getElementsByName){a=d.getElementsByName(b);c=a.length;for(var f=0;f<c;f++)if(a[f].getAttribute(\"name\")===b)if(!(e!=d&&!N(e,a[f])))return a[f]}a=d.getElementsByTagName(\"*\");return p(a,function(g){return U.b(b,g,e,d)})};U.a=function(a,b,c){var d=O(a),e=c||d;a=d.getElementsByTagName(\"*\");return o(a,function(f){return U.b(b,f,e,d)})};var V={};V.c=function(a,b,c){a=O(a);c=c||a;if(!j(a.evaluate))throw Error(\"XPath location is not supported\");if(!b)throw Error(\"No xpath specified\");return(b=a.evaluate(b,c,null,9,null).singleNodeValue)?b:null};V.a=function(a,b,c){a=O(a);c=c||a;if(!j(a.evaluate))throw Error(\"XPath location is not supported\");if(!b)throw Error(\"No xpath specified\");b=a.evaluate(b,c,null,5,null);c=[];for(a=b.iterateNext();a;){c.push(a);a=b.iterateNext()}return c};var W={className:Q,css:R,id:T,name:U,xpath:V};var X=function(a,b){a:{var c;b:{for(c in a){c=c;break b}c=void 0}if(c){var d=W[c];if(d&&j(d.a)){a=k(W[c].a,null,h,a[c],b);break a}}throw new Error(\"Unsupported locator strategy: \"+c);}return a()},Y=\"findElements\".split(\".\"),Z=h;!(Y[0]in Z)&&Z.execScript&&Z.execScript(\"var \"+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&X!==undefined)Z[$]=X;else Z=Z[$]?Z[$]:(Z[$]={});",
NULL
};

#endif
