/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef FINDELEMENT_H
#define FINDELEMENT_H

wchar_t* FINDELEMENT[] = {
L"var h=this;",
L"function aa(a){var b=typeof a;if(b==\"object\")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)==\"[object Array]\"||typeof a.length==\"number\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)==\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\")))return\"function\"}else return\"null\";else if(b==",
L"\"function\"&&typeof a.call==\"undefined\")return\"object\";return b}function i(a){return aa(a)==\"function\"}function ba(a,b){var c=b||h;if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,e);return a.apply(c,f)}}else return function(){return a.apply(c,arguments)}}var ca=Date.now||function(){return+new Date};var j=Array.prototype,k=j.indexOf?function(a,b,c){return j.indexOf.call(a,b,c)}:function(a,b,c){for(c=c==null?0:c<0?Math.max(0,a.length+c):c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},l=j.filter?function(a,b,c){return j.filter.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=[],d=0,g=typeof a==\"string\"?a.split(\"\"):a,n=0;n<e;n++)if(n in g){var A=g[n];if(b.call(c,A,n,a))f[d++]=A}return f};",
L"function m(a,b,c){a:{for(var e=a.length,f=typeof a==\"string\"?a.split(\"\"):a,d=0;d<e;d++)if(d in f&&b.call(c,f[d],d,a)){b=d;break a}b=-1}return b<0?null:typeof a==\"string\"?a.charAt(b):a[b]};function o(a,b){this.width=a;this.height=b}o.prototype.toString=function(){return\"(\"+this.width+\" x \"+this.height+\")\"};function p(a){return a.replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}",
L"function da(a,b){var c=0;a=p(String(a)).split(\".\");b=p(String(b)).split(\".\");for(var e=Math.max(a.length,b.length),f=0;c==0&&f<e;f++){var d=a[f]||\"\",g=b[f]||\"\",n=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),A=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var t=n.exec(d)||[\"\",\"\",\"\"],u=A.exec(g)||[\"\",\"\",\"\"];if(t[0].length==0&&u[0].length==0)break;c=q(t[1].length==0?0:parseInt(t[1],10),u[1].length==0?0:parseInt(u[1],10))||q(t[2].length==0,u[2].length==0)||q(t[2],u[2])}while(c==0)}return c}",
L"function q(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}ca();var r,s,v,w,x;function y(){return h.navigator?h.navigator.userAgent:null}x=w=v=s=r=false;var z;if(z=y()){var ea=h.navigator;r=z.indexOf(\"Opera\")==0;s=!r&&z.indexOf(\"MSIE\")!=-1;w=(v=!r&&z.indexOf(\"WebKit\")!=-1)&&z.indexOf(\"Mobile\")!=-1;x=!r&&!v&&ea.product==\"Gecko\"}var B=r,fa=s,ga=x,C=v,ha=w,D,E=\"\",F;",
L"if(B&&h.opera){var G=h.opera.version;E=typeof G==\"function\"?G():G}else{if(ga)F=/rv\\:([^\\);]+)(\\)|;)/;else if(fa)F=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(C)F=/WebKit\\/(\\S+)/;if(F){var H=F.exec(y());E=H?H[1]:\"\"}}D=E;var I={};function J(a){return I[a]||(I[a]=da(D,a)>=0)};function ia(a){if(a.parentWindow)return a.parentWindow;if(C&&!J(\"500\")&&!ha){var b=a.createElement(\"script\");b.innerHTML=\"document.parentWindow=window\";var c=a.documentElement;c.appendChild(b);c.removeChild(b);return a.parentWindow}return a.defaultView}var ja=C&&J(\"522\");",
L"function K(a,b){if(typeof a.contains!=\"undefined\"&&!ja&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!=\"undefined\")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function L(a){return a.nodeType==9?a:a.ownerDocument||a.document}function M(a){this.e=a||h.document||document}",
L"M.prototype.d=function(a,b,c){var e=this.e;c=c||e;a=a&&a!=\"*\"?a.toLowerCase():\"\";if(c.querySelectorAll&&(a||b)&&(!C||e.compatMode==\"CSS1Compat\"||J(\"528\")))b=c.querySelectorAll(a+(b?\".\"+b:\"\"));else if(b&&c.getElementsByClassName){e=c.getElementsByClassName(b);if(a){c={};for(var f=0,d=0,g;g=e[d];d++)if(a==g.nodeName.toLowerCase())c[f++]=g;c.length=f;b=c}else b=e}else{e=c.getElementsByTagName(a||\"*\");if(b){c={};for(d=f=0;g=e[d];d++){a=g.className;if(typeof a.split==\"function\"&&k(a.split(\" \"),b)>=0)c[f++]=",
L"g}c.length=f;b=c}else b=e}return b};M.prototype.createElement=function(a){return this.e.createElement(a)};M.prototype.appendChild=function(a,b){a.appendChild(b)};M.prototype.contains=K;var N={};N.c=function(a,b,c){return b==c||K(b,a)};N.a=function(a,b,c){if(!b)throw Error(\"No class name specified\");b=p(b);if(b.split(/\\s+/).length>1)throw Error(\"Compound class names not permitted\");var e=L(a),f=c||e;a=(new M(e)).d(\"*\",b);return m(a,function(d){return N.c(d,f,e)})};",
L"N.b=function(a,b,c){if(!b)throw Error(\"No class name specified\");b=p(b);if(b.split(/\\s+/).length>1)throw Error(\"Compound class names not permitted\");var e=L(a),f=c||e;a=(new M(e)).d(\"*\",b);return l(a,function(d){return N.c(d,f,e)})};var O={};O.a=function(a,b,c){a=c||L(a);if(!i(a.querySelector))throw Error(\"CSS selection is not supported\");if(!b)throw Error(\"No selector specified\");if(b.split(/,/).length>1)throw Error(\"Compound selectors not permitted\");b=p(b);return(b=a.querySelector(b))?b:null};O.b=function(a,b,c){a=c||L(a);if(!i(a.querySelectorAll))throw Error(\"CSS selection is not supported\");if(!b)throw Error(\"No selector specified\");if(b.split(/,/).length>1)throw Error(\"Compound selectors not permitted\");b=p(b);return a.querySelectorAll(b)};function P(a,b){var c=L(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(a=c.defaultView.getComputedStyle(a,\"\"))return a[b];return null}",
L"function ka(a){var b=B&&!J(\"10\");if((P(a,\"display\")||(a.currentStyle?a.currentStyle.display:null)||a.style.display)!=\"none\")return b?new o(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new o(a.offsetWidth,a.offsetHeight);var c=a.style,e=c.display,f=c.visibility,d=c.position;c.visibility=\"hidden\";c.position=\"absolute\";c.display=\"inline\";if(b){b=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{b=a.offsetWidth;a=a.offsetHeight}c.display=e;c.position=d;c.visibility=f;",
L"return new o(b,a)};function la(a,b){if(i(a.hasAttribute))if(a.hasAttribute(b))return true;if(a[b]!==undefined)return true;for(var c in a)if(b==c)return true;return false}var ma=[\"checked\",\"disabled\",\"readOnly\",\"selected\"];",
L"function Q(a,b){if(!a)throw Error(\"Element has not been specified\");if(!b)throw Error(\"Attribute name must be set\");var c=b.toLowerCase();if(k(ma,b)>=0){a=a[b];return!!(a&&a!=\"false\")}if(\"style\"==c){a=a.style;return a.cssText?a.cssText:\"\"}if(\"class\"==c)b=\"className\";if(\"readonly\"==c)b=\"readOnly\";if(!la(a,b))return null;return a[b]===undefined?a.getAttribute(b):a[b]}",
L"function R(a){a=a.parentNode;if(!a)return null;for(;a.nodeType!=1&&!(a.nodeType==9||a.nodeType==11);)a=a.parentNode;return a&&a.nodeType==1?a:null}",
L"function na(a){a=R(a);if(!a)throw new Error(\"No value given for isDisplayed required parameter\");var b=L(a)?ia(L(a)):window;function c(f,d){if(b.getComputedStyle)return P(f,d);return f.currentStyle?f.currentStyle[d]:null}function e(f){if(c(f,\"display\")==\"none\")return false;f=R(f);return!f||e(f)}if(!(function(f){f.tagName||alert(f);if(f.tagName.toLowerCase()==\"input\"&&f.type.toLowerCase()==\"hidden\")return false;return c(f,\"visibility\")!=\"hidden\"}(a)&&e(a)))return false;a=ka(a);return a.height>0&&a.width>",
L"0}",
L"function S(a,b,c){if(a.tagName&&a.tagName==\"SCRIPT\")return[b,c];else if(a.tagName&&a.tagName==\"TITLE\")return[c+a.text,\"\"];for(var e=a.childNodes,f=0;f<e.length;f++){var d=e[f];if(d.tagName&&d.tagName==\"PRE\"){b+=c.replace(/\\s+/g,\" \");c=\"\";d=S(d,b,\"\",true);b+=d[1]}else if(d.nodeName==\"#text\"){if(na(d)){d=d.nodeValue;d=d.replace(new RegExp(String.fromCharCode(160),\"gm\"),\" \");c+=d}}else{d=S(d,b,c,false);b=d[0];c=d[1]}}if(a.tagName&&a.tagName==\"BR\"?true:false)if(a.tagName&&a.tagName!=\"PRE\"){b+=c.replace(/\\s+/g,\" \")+",
L"\"\\n\";c=\"\"}else b+=\"\\n\";return[b,c]}function oa(a){return a==\"\\n\"||a==\" \"||a==\"\\t\"||a==\"\\r\"}function pa(a){a=S(a,\"\",\"\",a.tagName==\"PRE\");a=a[0]+a[1].replace(/\\s+/g,\" \");for(var b=0;b<a.length&&oa(a[b]);)++b;for(var c=a.length;c>b&&oa(a[c-1]);)--c;return a.slice(b,c)};var T={};T.a=function(a,b,c){a=L(a);c=c||a;var e=a.getElementById(b);if(!e)return null;if(e.getAttribute(\"id\")==b&&K(c,e))return e;a=a.getElementsByTagName(\"*\");e=a.length;for(var f=0;f<e;f++){var d=a[f];if(d.tagName.toLowerCase()==\"form\"){if(d.attributes.id.nodeValue==b&&K(c,d))return d}else if(Q(d,\"id\")==b&&K(c,d))return d}return null};T.b=function(a,b,c){a=L(a);var e=c||a;c=a.getElementsByTagName(\"*\");return l(c,function(f){return Q(f,\"id\")==b&&K(e,f)})};var U={},V={};U.g=function(a,b,c,e){if(!b)throw Error(\"No link text specified\");a=L(a);var f=c||a;c=(new M(a)).d(\"A\");return m(c,function(d){var g=pa(d);if(e&&g.indexOf(b)!=-1||g==b)return K(f,d)})};U.f=function(a,b,c,e){if(!b)throw Error(\"No link text specified\");a=L(a);var f=c||a;c=(new M(a)).d(\"A\");return l(c,function(d){var g=pa(d);if(e&&g.indexOf(b)!=-1||g==b)return K(f,d)})};U.a=function(a,b,c){return U.g(a,b,c,false)};U.b=function(a,b,c){return U.f(a,b,c,false)};",
L"V.a=function(a,b,c){return U.g(a,b,c,true)};V.b=function(a,b,c){return U.f(a,b,c,true)};var W={};W.c=function(a,b,c,e){if(Q(b,\"name\")==a)return c==e||K(c,b);return false};W.a=function(a,b,c){var e=L(a),f=c||e;if(e.getElementsByName){a=e.getElementsByName(b);c=a.length;for(var d=0;d<c;d++)if(a[d].getAttribute(\"name\")===b)if(!(f!=e&&!K(f,a[d])))return a[d]}a=e.getElementsByTagName(\"*\");return m(a,function(g){return W.c(b,g,f,e)})};W.b=function(a,b,c){var e=L(a),f=c||e;a=e.getElementsByTagName(\"*\");return l(a,function(d){return W.c(b,d,f,e)})};var X={};X.a=function(a,b,c){a=L(a);c=c||a;if(!i(a.evaluate))throw Error(\"XPath location is not supported\");if(!b)throw Error(\"No xpath specified\");return(b=a.evaluate(b,c,null,9,null).singleNodeValue)?b:null};X.b=function(a,b,c){a=L(a);c=c||a;if(!i(a.evaluate))throw Error(\"XPath location is not supported\");if(!b)throw Error(\"No xpath specified\");b=a.evaluate(b,c,null,5,null);c=[];for(a=b.iterateNext();a;){c.push(a);a=b.iterateNext()}return c};var qa={className:N,css:O,id:T,link:U,name:W,partialLink:V,xpath:X};var ra=function(a,b){a:{var c;b:{for(c in a){c=c;break b}c=void 0}if(c){var e=qa[c];if(e&&i(e.a)){a=ba(e.a,null,h,a[c],b);break a}}throw new Error(\"Unsupported locator strategy: \"+c);}return a()},Y=\"findElement\".split(\".\"),Z=h;!(Y[0]in Z)&&Z.execScript&&Z.execScript(\"var \"+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&ra!==undefined)Z[$]=ra;else Z=Z[$]?Z[$]:(Z[$]={});",
NULL
};

#endif
