/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef FIRE_H
#define FIRE_H

wchar_t* FIRE[] = {
L"var h,n=this;function aa(a,b){a=a.split(\".\");b=b||n;for(var c;c=a.shift();)if(b[c])b=b[c];else return null;return b}function p(){}",
L"function q(a){var b=typeof a;if(b==\"object\")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)==\"[object Array]\"||typeof a.length==\"number\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)==\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\")))return\"function\"}else return\"null\";",
L"else if(b==\"function\"&&typeof a.call==\"undefined\")return\"object\";return b}function ba(a){if(a.hasOwnProperty&&a.hasOwnProperty(r))return a[r];a[r]||(a[r]=++ca);return a[r]}var r=\"closure_hashCode_\"+Math.floor(Math.random()*2147483648).toString(36),ca=0;function s(a,b){function c(){}c.prototype=b.prototype;a.t=b.prototype;a.prototype=new c};var t=Array.prototype,da=t.indexOf?function(a,b,c){return t.indexOf.call(a,b,c)}:function(a,b,c){for(c=c==null?0:c<0?Math.max(0,a.length+c):c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};function ea(a,b){var c=0;a=String(a).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");b=String(b).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");for(var d=Math.max(a.length,b.length),e=0;c==0&&e<d;e++){var f=a[e]||\"\",j=b[e]||\"\",g=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),o=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var i=g.exec(f)||[\"\",\"\",\"\"],k=o.exec(j)||[\"\",\"\",\"\"];if(i[0].length==0&&k[0].length==0)break;c=u(i[1].length==0?0:parseInt(i[1],10),k[1].length==0?0:parseInt(k[1],10))||u(i[2].length==0,k[2].length==0)||u(i[2],",
L"k[2])}while(c==0)}return c}function u(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}(Date.now||function(){return+new Date})();var v,w,x,y,z;function fa(){return n.navigator?n.navigator.userAgent:null}z=y=x=w=v=false;var A;if(A=fa()){var ga=n.navigator;v=A.indexOf(\"Opera\")==0;w=!v&&A.indexOf(\"MSIE\")!=-1;y=(x=!v&&A.indexOf(\"WebKit\")!=-1)&&A.indexOf(\"Mobile\")!=-1;z=!v&&!x&&ga.product==\"Gecko\"}var B=w,ha=z,C=x,ia=y,ja,D=\"\",E;",
L"if(v&&n.opera){var F=n.opera.version;D=typeof F==\"function\"?F():F}else{if(ha)E=/rv\\:([^\\);]+)(\\)|;)/;else if(B)E=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(C)E=/WebKit\\/(\\S+)/;if(E){var ka=E.exec(fa());D=ka?ka[1]:\"\"}}ja=D;var la={};function G(a){return la[a]||(la[a]=ea(ja,a)>=0)};function H(a){if(a.parentWindow)return a.parentWindow;if(C&&!G(\"500\")&&!ia){var b=a.createElement(\"script\");b.innerHTML=\"document.parentWindow=window\";var c=a.documentElement;c.appendChild(b);c.removeChild(b);return a.parentWindow}return a.defaultView}C&&G(\"522\");function I(a){return a.nodeType==9?a:a.ownerDocument||a.document};function J(){}J.prototype.n=false;J.prototype.g=function(){if(!this.n){this.n=true;this.d()}};J.prototype.d=function(){};function K(a,b){this.type=a;this.currentTarget=this.target=b}s(K,J);K.prototype.d=function(){delete this.type;delete this.target;delete this.currentTarget};K.prototype.k=false;K.prototype.v=true;function L(a,b){a&&this.i(a,b)}s(L,K);h=L.prototype;h.target=null;h.relatedTarget=null;h.offsetX=0;h.offsetY=0;h.clientX=0;h.clientY=0;h.screenX=0;h.screenY=0;h.button=0;h.keyCode=0;h.charCode=0;h.ctrlKey=false;h.altKey=false;h.shiftKey=false;h.metaKey=false;h.o=null;",
L"h.i=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(ha)try{b=b.nodeName&&b}catch(d){}}else if(c==\"mouseover\")b=a.fromElement;else if(c==\"mouseout\")b=a.toElement;this.relatedTarget=b;this.offsetX=a.offsetX!==undefined?a.offsetX:a.layerX;this.offsetY=a.offsetY!==undefined?a.offsetY:a.layerY;this.clientX=a.clientX!==undefined?a.clientX:a.pageX;this.clientY=a.clientY!==undefined?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=",
L"a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c==\"keypress\"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.o=a;delete this.v;delete this.k};B&&G(\"8\");L.prototype.d=function(){L.t.d.call(this);this.relatedTarget=this.currentTarget=this.target=this.o=null};function ma(){}var na=0;h=ma.prototype;h.key=0;h.f=false;h.l=false;h.i=function(a,b,c,d,e,f){if(q(a)==\"function\")this.p=true;else if(a&&a.handleEvent&&q(a.handleEvent)==\"function\")this.p=false;else throw Error(\"Invalid listener argument\");this.j=a;this.s=b;this.src=c;this.type=d;this.capture=!!e;this.u=f;this.l=false;this.key=++na;this.f=false};h.handleEvent=function(a){if(this.p)return this.j.call(this.u||this.src,a);return this.j.handleEvent.call(this.j,a)};function M(a,b){this.q=b;this.b=[];if(a>this.q)throw Error(\"[goog.structs.SimplePool] Initial cannot be greater than max\");for(b=0;b<a;b++)this.b.push(this.a?this.a():{})}s(M,J);M.prototype.a=null;M.prototype.m=null;function oa(a){if(a.b.length)return a.b.pop();return a.a?a.a():{}}function N(a,b){a.b.length<a.q?a.b.push(b):pa(a,b)}function pa(a,b){if(a.m)a.m(b);else if(q(b.g)==\"function\")b.g();else for(var c in b)delete b[c]}",
L"M.prototype.d=function(){M.t.d.call(this);for(var a=this.b;a.length;)pa(this,a.pop());delete this.b};var qa;var ra=(qa=\"ScriptEngine\"in n&&n.ScriptEngine()==\"JScript\")?n.ScriptEngineMajorVersion()+\".\"+n.ScriptEngineMinorVersion()+\".\"+n.ScriptEngineBuildVersion():\"0\";var O,P,Q,sa,R,S,T,ta;",
L"(function(){function a(){return{c:0,e:0}}function b(){return[]}function c(){function l(Aa){return j.call(l.src,l.key,Aa)}return l}function d(){return new ma}function e(){return new L}var f=qa&&!(ea(ra,\"5.7\")>=0),j;sa=function(l){j=l};if(f){O=function(l){N(g,l)};P=function(){return oa(o)};Q=function(l){N(o,l)};R=function(){N(i,c())};S=function(l){N(k,l)};T=function(){return oa(m)};ta=function(l){N(m,l)};var g=new M(0,600);g.a=a;var o=new M(0,600);o.a=b;var i=new M(0,600);i.a=c;var k=new M(0,600);k.a=",
L"d;var m=new M(0,600);m.a=e}else{O=p;P=b;S=R=Q=p;T=e;ta=p}})();var U={},V={},ua={},va={};function wa(a){if(!U[a])return false;var b=U[a];if(b.f)return false;var c=b.src,d=b.type,e=b.s,f=b.capture;if(c.removeEventListener){if(c==n||!c.A)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(xa(d),e);c=ba(c);e=V[d][f][c];if(ua[c]){var j=ua[c],g=da(j,b);g>=0&&t.splice.call(j,g,1);j.length==0&&delete ua[c]}b.f=true;e.r=true;ya(d,f,c,e);delete U[a];return true}",
L"function ya(a,b,c,d){if(!d.h)if(d.r){for(var e=0,f=0;e<d.length;e++)if(d[e].f){var j=d[e].s;j.src=null;R(j);S(d[e])}else{if(e!=f)d[f]=d[e];f++}d.length=f;d.r=false;if(f==0){Q(d);delete V[a][b][c];V[a][b].c--;if(V[a][b].c==0){O(V[a][b]);delete V[a][b];V[a].c--}if(V[a].c==0){O(V[a]);delete V[a]}}}}function xa(a){if(a in va)return va[a];return va[a]=\"on\"+a}",
L"function za(a,b,c,d,e){var f=1;b=ba(b);if(a[b]){a.e--;a=a[b];if(a.h)a.h++;else a.h=1;try{for(var j=a.length,g=0;g<j;g++){var o=a[g];if(o&&!o.f)f&=Ba(o,e)!==false}}finally{a.h--;ya(c,d,b,a)}}return Boolean(f)}function Ba(a,b){b=a.handleEvent(b);a.l&&wa(a.key);return b}",
L"sa(function(a,b){if(!U[a])return true;a=U[a];var c=a.type,d=V;if(!(c in d))return true;d=d[c];var e,f;if(B){e=b||aa(\"window.event\");b=true in d;var j=false in d;if(b){if(e.keyCode<0||e.returnValue!=undefined)return true;a:{var g=false;if(e.keyCode==0)try{e.keyCode=-1;break a}catch(o){g=true}if(g||e.returnValue==undefined)e.returnValue=true}}g=T();g.i(e,this);e=true;try{if(b){for(var i=P(),k=g.currentTarget;k;k=k.parentNode)i.push(k);f=d[true];f.e=f.c;for(var m=i.length-1;!g.k&&m>=0&&f.e;m--){g.currentTarget=",
L"i[m];e&=za(f,i[m],c,true,g)}if(j){f=d[false];f.e=f.c;for(m=0;!g.k&&m<i.length&&f.e;m++){g.currentTarget=i[m];e&=za(f,i[m],c,false,g)}}}else e=Ba(a,g)}finally{if(i){i.length=0;Q(i)}g.g();ta(g)}return e}f=new L(b,this);try{e=Ba(a,f)}finally{f.g()}return e});var Ca=B?0:1,Da=[\"dragstart\",\"dragexit\",\"mouseover\",\"mouseout\"];",
L"function W(a,b,c){var d=I(a),e=d?H(d):window;c=c||{};var f=c.x||0,j=c.y||0,g=c.button||Ca,o=c.bubble||true,i=null;if(da(Da,b)>=0)i=c.related||null;var k=!!c.alt,m=!!c.control,l=!!c.shift;c=!!c.meta;if(a.fireEvent&&d&&d.createEventObject){a=d.createEventObject();a.altKey=k;a.w=m;a.metaKey=c;a.shiftKey=l;a.clientX=f;a.clientY=j;a.button=g;a.relatedTarget=i}else{a=d.createEvent(\"MouseEvents\");if(a.initMouseEvent)a.initMouseEvent(b,o,true,e,1,0,0,f,j,m,k,l,c,g,i);else{a.initEvent(b,o,true);a.shiftKey=",
L"l;a.metaKey=c;a.altKey=k;a.ctrlKey=m;a.button=g}}return a}function Ea(a,b,c){var d=I(a);d&&H(d);c=c||{};var e=c.bubble||true,f=!!c.alt,j=!!c.control,g=!!c.shift;c=!!c.meta;if(a.fireEvent&&d&&d.createEventObject){a=d.createEventObject();a.altKey=f;a.z=j;a.metaKey=c;a.shiftKey=g}else{a=d.createEvent(\"HTMLEvents\");a.initEvent(b,e,true);a.shiftKey=g;a.metaKey=c;a.altKey=f;a.ctrlKey=j}return a}var X={};X.mousedown=W;X.mousemove=W;X.mouseout=W;X.mouseover=W;X.mouseup=W;function Fa(a,b,c){c=(X[b]||Ea)(a,b,c);if(a.fireEvent){try{(I(a)?H(I(a)):window).event=c}catch(d){}a.fireEvent(\"on\"+b,c)}else a.dispatchEvent(c)}var Y=\"fire\".split(\".\"),Z=n;!(Y[0]in Z)&&Z.execScript&&Z.execScript(\"var \"+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&Fa!==undefined)Z[$]=Fa;else Z=Z[$]?Z[$]:(Z[$]={});",
NULL
};

#endif
