/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef GETLOCATION_H
#define GETLOCATION_H

wchar_t* GETLOCATION[] = {
L"var f=this,g=Date.now||function(){return+new Date};var j;function k(a,b){this.x=a!==undefined?a:0;this.y=b!==undefined?b:0}k.prototype.toString=function(){return\"(\"+this.x+\", \"+this.y+\")\"};function n(a,b){var c=0;a=String(a).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");b=String(b).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");for(var e=Math.max(a.length,b.length),h=0;c==0&&h<e;h++){var d=a[h]||\"\",i=b[h]||\"\",M=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),N=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var l=M.exec(d)||[\"\",\"\",\"\"],m=N.exec(i)||[\"\",\"\",\"\"];if(l[0].length==0&&m[0].length==0)break;c=o(l[1].length==0?0:parseInt(l[1],10),m[1].length==0?0:parseInt(m[1],10))||o(l[2].length==0,m[2].length==0)||o(l[2],",
L"m[2])}while(c==0)}return c}function o(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}g();var p,q,r,s;function t(){return f.navigator?f.navigator.userAgent:null}s=r=q=p=false;var u;if(u=t()){var v=f.navigator;p=u.indexOf(\"Opera\")==0;q=!p&&u.indexOf(\"MSIE\")!=-1;r=!p&&u.indexOf(\"WebKit\")!=-1;s=!p&&!r&&v.product==\"Gecko\"}var w=p,x=q,y=s,z=r,A,B=\"\",C;if(w&&f.opera){var D=f.opera.version;B=typeof D==\"function\"?D():D}else{if(y)C=/rv\\:([^\\);]+)(\\)|;)/;else if(x)C=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(z)C=/WebKit\\/(\\S+)/;if(C){var E=C.exec(t());B=E?E[1]:\"\"}}A=B;var F={};z&&(F[\"522\"]||(F[\"522\"]=n(A,\"522\")>=0));function G(a){return a.nodeType==9?a:a.ownerDocument||a.document}function H(a){this.a=a||f.document||document}function I(a){return a.a.compatMode==\"CSS1Compat\"};function J(a,b){var c;a:{c=G(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaultView.getComputedStyle(a,\"\")){c=c[b];break a}c=null}return c||(a.currentStyle?a.currentStyle[b]:null)||a.style[b]}",
L"function K(a){if(x)return a.offsetParent;var b=G(a),c=J(a,\"position\"),e=c==\"fixed\"||c==\"absolute\";for(a=a.parentNode;a&&a!=b;a=a.parentNode){c=J(a,\"position\");e=e&&c==\"static\"&&a!=b.documentElement&&a!=b.body;if(!e&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||c==\"fixed\"||c==\"absolute\"))return a}return null};var L=function(a){var b,c=G(a),e=J(a,\"position\"),h=y&&c.getBoxObjectFor&&!a.getBoundingClientRect&&e==\"absolute\"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),d=new k(0,0),i;b=c?c.nodeType==9?c:G(c):document;i=x&&!I(b?new H(G(b)):j||(j=new H))?b.body:b.documentElement;if(a==i)return d;if(a.getBoundingClientRect){b=a.getBoundingClientRect();if(x){a=a.ownerDocument;b.left-=a.documentElement.clientLeft+a.body.clientLeft;b.top-=a.documentElement.clientTop+a.body.clientTop}b=b;c=(c?new H(G(c)):",
L"j||(j=new H)).a;c=!z&&c.compatMode==\"CSS1Compat\"?c.documentElement:c.body;c=new k(c.scrollLeft,c.scrollTop);d.x=b.left+c.x;d.y=b.top+c.y}else if(c.getBoxObjectFor&&!h){b=c.getBoxObjectFor(a);c=c.getBoxObjectFor(i);d.x=b.screenX-c.screenX;d.y=b.screenY-c.screenY}else{b=a;do{d.x+=b.offsetLeft;d.y+=b.offsetTop;if(b!=a){d.x+=b.clientLeft||0;d.y+=b.clientTop||0}if(z&&J(b,\"position\")==\"fixed\"){d.x+=c.body.scrollLeft;d.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(w||z&&e==\"absolute\")d.y-=",
L"c.body.offsetTop;for(b=a;(b=K(b))&&b!=c.body&&b!=i;){d.x-=b.scrollLeft;if(!w||b.tagName!=\"TR\")d.y-=b.scrollTop}}return d},O=\"getLocation\".split(\".\"),P=f;!(O[0]in P)&&P.execScript&&P.execScript(\"var \"+O[0]);for(var Q;O.length&&(Q=O.shift());)if(!O.length&&L!==undefined)P[Q]=L;else P=P[Q]?P[Q]:(P[Q]={});",
NULL
};

#endif
