/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef GETLOCATION_H
#define GETLOCATION_H

wchar_t* GETLOCATION[] = {
L"var g=this,h=Date.now||function(){return+new Date};var j;function m(a,c){this.x=a!==undefined?a:0;this.y=c!==undefined?c:0}m.prototype.toString=function(){return\"(\"+this.x+\", \"+this.y+\")\"};function n(a,c){var d=0;a=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,\"\").split(\".\");c=String(c).replace(/^[\s\xa0]+|[\s\xa0]+$/g,\"\").split(\".\");for(var b=Math.max(a.length,c.length),e=0;d==0&&e<b;e++){var s=a[e]||\"\",y=c[e]||\"\",f=new RegExp(\"(\\d*)(\\D*)\",\"g\"),i=new RegExp(\"(\\d*)(\\D*)\",\"g\");do{var k=f.exec(s)||[\"\",\"\",\"\"],l=i.exec(y)||[\"\",\"\",\"\"];if(k[0].length==0&&l[0].length==0)break;d=o(k[1].length==0?0:parseInt(k[1],10),l[1].length==0?0:parseInt(l[1],10))||o(k[2].length==0,l[2].length==0)||o(k[2],",
L"l[2])}while(d==0)}return d}function o(a,c){if(a<c)return-1;else if(a>c)return 1;return 0}h();var p,q,r,t;function u(){return g.navigator?g.navigator.userAgent:null}t=r=q=p=false;var v;if(v=u()){var w=g.navigator;p=v.indexOf(\"Opera\")==0;q=!p&&v.indexOf(\"MSIE\")!=-1;r=!p&&v.indexOf(\"WebKit\")!=-1;t=!p&&!r&&w.product==\"Gecko\"}var x=p,z=q,A=t,B=r,C,D=\"\",E;if(x&&g.opera){var F=g.opera.version;D=typeof F==\"function\"?F():F}else{if(A)E=/rv\:([^\);]+)(\)|;)/;else if(z)E=/MSIE\s+([^\);]+)(\)|;)/;else if(B)E=/WebKit\/(\S+)/;if(E){var G=E.exec(u());D=G?G[1]:\"\"}}C=D;var H={};function I(a){return a?new J(K(a)):j||(j=new J)}B&&(H[\"522\"]||(H[\"522\"]=n(C,\"522\")>=0));function K(a){return a.nodeType==9?a:a.ownerDocument||a.document}function J(a){this.a=a||g.document||document}function L(a){return a.a.compatMode==\"CSS1Compat\"}function M(a){a=!B&&a.a.compatMode==\"CSS1Compat\"?a.a.documentElement:a.a.body;return new m(a.scrollLeft,a.scrollTop)};function N(a,c){var d;a:{d=K(a);if(d.defaultView&&d.defaultView.getComputedStyle)if(d=d.defaultView.getComputedStyle(a,\"\")){d=d[c];break a}d=null}return d||(a.currentStyle?a.currentStyle[c]:null)||a.style[c]}function O(a){var c=a.getBoundingClientRect();if(z){a=a.ownerDocument;c.left-=a.documentElement.clientLeft+a.body.clientLeft;c.top-=a.documentElement.clientTop+a.body.clientTop}return c}",
L"function P(a){if(z)return a.offsetParent;var c=K(a),d=N(a,\"position\"),b=d==\"fixed\"||d==\"absolute\";for(a=a.parentNode;a&&a!=c;a=a.parentNode){d=N(a,\"position\");b=b&&d==\"static\"&&a!=c.documentElement&&a!=c.body;if(!b&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||d==\"fixed\"||d==\"absolute\"))return a}return null};var Q=function(a){var c=new m;if(a.nodeType==1)if(a.getBoundingClientRect){var d=O(a);c.x=d.left;c.y=d.top}else{d=M(I(a));var b,e=K(a),s=N(a,\"position\"),y=A&&e.getBoxObjectFor&&!a.getBoundingClientRect&&s==\"absolute\"&&(b=e.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),f=new m(0,0),i;b=e?e.nodeType==9?e:K(e):document;i=z&&!L(I(b))?b.body:b.documentElement;if(a!=i)if(a.getBoundingClientRect){b=O(a);e=M(I(e));f.x=b.left+e.x;f.y=b.top+e.y}else if(e.getBoxObjectFor&&!y){b=e.getBoxObjectFor(a);e=e.getBoxObjectFor(i);",
L"f.x=b.screenX-e.screenX;f.y=b.screenY-e.screenY}else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;if(b!=a){f.x+=b.clientLeft||0;f.y+=b.clientTop||0}if(B&&N(b,\"position\")==\"fixed\"){f.x+=e.body.scrollLeft;f.y+=e.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(x||B&&s==\"absolute\")f.y-=e.body.offsetTop;for(b=a;(b=P(b))&&b!=e.body&&b!=i;){f.x-=b.scrollLeft;if(!x||b.tagName!=\"TR\")f.y-=b.scrollTop}}c.x=f.x-d.x;c.y=f.y-d.y}else{c.x=a.clientX;c.y=a.clientY}a=I(a).b;c.x+=a.x;c.y+=a.y;return c},R=\"getLocation\".split(\".\"),",
L"S=g;!(R[0]in S)&&S.execScript&&S.execScript(\"var \"+R[0]);for(var T;R.length&&(T=R.shift());)if(!R.length&&Q!==undefined)S[T]=Q;else S=S[T]?S[T]:(S[T]={});",
NULL
};

#endif
