/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef GETVISIBLETEXT_H
#define GETVISIBLETEXT_H

wchar_t* GETVISIBLETEXT[] = {
L"var g=this,h=Date.now||function(){return+new Date};function i(a,c){this.width=a;this.height=c}i.prototype.toString=function(){return\"(\"+this.width+\" x \"+this.height+\")\"};function l(a,c){var b=0;a=String(a).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");c=String(c).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");for(var f=Math.max(a.length,c.length),d=0;b==0&&d<f;d++){var e=a[d]||\"\",L=c[d]||\"\",M=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),N=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var j=M.exec(e)||[\"\",\"\",\"\"],k=N.exec(L)||[\"\",\"\",\"\"];if(j[0].length==0&&k[0].length==0)break;b=m(j[1].length==0?0:parseInt(j[1],10),k[1].length==0?0:parseInt(k[1],10))||m(j[2].length==0,k[2].length==0)||m(j[2],",
L"k[2])}while(b==0)}return b}function m(a,c){if(a<c)return-1;else if(a>c)return 1;return 0}h();var n,o,p,q,r;function s(){return g.navigator?g.navigator.userAgent:null}r=q=p=o=n=false;var t;if(t=s()){var u=g.navigator;n=t.indexOf(\"Opera\")==0;o=!n&&t.indexOf(\"MSIE\")!=-1;q=(p=!n&&t.indexOf(\"WebKit\")!=-1)&&t.indexOf(\"Mobile\")!=-1;r=!n&&!p&&u.product==\"Gecko\"}var v=n,w=o,x=r,y=p,z=q,A,B=\"\",C;if(v&&g.opera){var D=g.opera.version;B=typeof D==\"function\"?D():D}else{if(x)C=/rv\\:([^\\);]+)(\\)|;)/;else if(w)C=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(y)C=/WebKit\\/(\\S+)/;if(C){var E=C.exec(s());B=E?E[1]:\"\"}}A=B;",
L"var F={};function G(a){return F[a]||(F[a]=l(A,a)>=0)};function H(a){if(a.parentWindow)return a.parentWindow;if(y&&!G(\"500\")&&!z){var c=a.createElement(\"script\");c.innerHTML=\"document.parentWindow=window\";var b=a.documentElement;b.appendChild(c);b.removeChild(c);return a.parentWindow}return a.defaultView}y&&G(\"522\");function I(a,c){var b=a.nodeType==9?a:a.ownerDocument||a.document;if(b.defaultView&&b.defaultView.getComputedStyle)if(a=b.defaultView.getComputedStyle(a,\"\"))return a[c];return null}",
L"function J(a){var c=v&&!G(\"10\");if((I(a,\"display\")||(a.currentStyle?a.currentStyle.display:null)||a.style.display)!=\"none\")return c?new i(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new i(a.offsetWidth,a.offsetHeight);var b=a.style,f=b.display,d=b.visibility,e=b.position;b.visibility=\"hidden\";b.position=\"absolute\";b.display=\"inline\";if(c){c=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{c=a.offsetWidth;a=a.offsetHeight}b.display=f;b.position=e;b.visibility=d;return new i(c,",
L"a)};function K(a){a=a.parentNode;if(!a)return null;for(;a.nodeType!=1&&!(a.nodeType==9||a.nodeType==11);)a=a.parentNode;return a&&a.nodeType==1?a:null}",
L"function O(a){a=K(a);if(!a)throw new Error(\"No value given for isDisplayed required parameter\");var c=(a.nodeType==9?a:a.ownerDocument||a.document)?H(a.nodeType==9?a:a.ownerDocument||a.document):window;function b(d,e){if(c.getComputedStyle)return I(d,e);return d.currentStyle?d.currentStyle[e]:null}function f(d){if(b(d,\"display\")==\"none\")return false;d=K(d);return!d||f(d)}if(!(function(d){d.tagName||alert(d);if(d.tagName.toLowerCase()==\"input\"&&d.type.toLowerCase()==\"hidden\")return false;return b(d,",
L"\"visibility\")!=\"hidden\"}(a)&&f(a)))return false;a=J(a);return a.height>0&&a.width>0}",
L"function P(a,c,b){if(a.tagName&&a.tagName==\"SCRIPT\")return[c,b];else if(a.tagName&&a.tagName==\"TITLE\")return[b+a.text,\"\"];for(var f=a.childNodes,d=0;d<f.length;d++){var e=f[d];if(e.tagName&&e.tagName==\"PRE\"){c+=b.replace(/\\s+/g,\" \");b=\"\";e=P(e,c,\"\",true);c+=e[1]}else if(e.nodeName==\"#text\"){if(O(e)){e=e.nodeValue;e=e.replace(new RegExp(String.fromCharCode(160),\"gm\"),\" \");b+=e}}else{e=P(e,c,b,false);c=e[0];b=e[1]}}if(a.tagName&&a.tagName==\"BR\"?true:false)if(a.tagName&&a.tagName!=\"PRE\"){c+=b.replace(/\\s+/g,",
L"\" \")+\"\\n\";b=\"\"}else c+=\"\\n\";return[c,b]}function Q(a){return a==\"\\n\"||a==\" \"||a==\"\\t\"||a==\"\\r\"};var R=function(a){a=P(a,\"\",\"\",a.tagName==\"PRE\");a=a[0]+a[1].replace(/\\s+/g,\" \");for(var c=0;c<a.length&&Q(a[c]);)++c;for(var b=a.length;b>c&&Q(a[b-1]);)--b;return a.slice(c,b)},S=\"getVisibleText\".split(\".\"),T=g;!(S[0]in T)&&T.execScript&&T.execScript(\"var \"+S[0]);for(var U;S.length&&(U=S.shift());)if(!S.length&&R!==undefined)T[U]=R;else T=T[U]?T[U]:(T[U]={});",
NULL
};

#endif
