/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/js_to_header.rb instead. */

#ifndef ISDISPLAYED_H
#define ISDISPLAYED_H

wchar_t* ISDISPLAYED[] = {
L"var e=this,f=Date.now||function(){return+new Date};function i(a,c){this.width=a;this.height=c}i.prototype.toString=function(){return\"(\"+this.width+\" x \"+this.height+\")\"};function l(a,c){var b=0;a=String(a).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");c=String(c).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\");for(var g=Math.max(a.length,c.length),d=0;b==0&&d<g;d++){var h=a[d]||\"\",J=c[d]||\"\",K=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),L=new RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var j=K.exec(h)||[\"\",\"\",\"\"],k=L.exec(J)||[\"\",\"\",\"\"];if(j[0].length==0&&k[0].length==0)break;b=m(j[1].length==0?0:parseInt(j[1],10),k[1].length==0?0:parseInt(k[1],10))||m(j[2].length==0,k[2].length==0)||m(j[2],",
L"k[2])}while(b==0)}return b}function m(a,c){if(a<c)return-1;else if(a>c)return 1;return 0}f();var n,o,p,q,r;function s(){return e.navigator?e.navigator.userAgent:null}r=q=p=o=n=false;var t;if(t=s()){var u=e.navigator;n=t.indexOf(\"Opera\")==0;o=!n&&t.indexOf(\"MSIE\")!=-1;q=(p=!n&&t.indexOf(\"WebKit\")!=-1)&&t.indexOf(\"Mobile\")!=-1;r=!n&&!p&&u.product==\"Gecko\"}var v=n,w=o,x=r,y=p,z=q,A,B=\"\",C;if(v&&e.opera){var D=e.opera.version;B=typeof D==\"function\"?D():D}else{if(x)C=/rv\\:([^\\);]+)(\\)|;)/;else if(w)C=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(y)C=/WebKit\\/(\\S+)/;if(C){var E=C.exec(s());B=E?E[1]:\"\"}}A=B;",
L"var F={};function G(a){return F[a]||(F[a]=l(A,a)>=0)};function H(a){if(a.parentWindow)return a.parentWindow;if(y&&!G(\"500\")&&!z){var c=a.createElement(\"script\");c.innerHTML=\"document.parentWindow=window\";var b=a.documentElement;b.appendChild(c);b.removeChild(c);return a.parentWindow}return a.defaultView}y&&G(\"522\");function I(a,c){var b=a.nodeType==9?a:a.ownerDocument||a.document;if(b.defaultView&&b.defaultView.getComputedStyle)if(a=b.defaultView.getComputedStyle(a,\"\"))return a[c];return null}",
L"function M(a){var c=v&&!G(\"10\");if((I(a,\"display\")||(a.currentStyle?a.currentStyle.display:null)||a.style.display)!=\"none\")return c?new i(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new i(a.offsetWidth,a.offsetHeight);var b=a.style,g=b.display,d=b.visibility,h=b.position;b.visibility=\"hidden\";b.position=\"absolute\";b.display=\"inline\";if(c){c=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{c=a.offsetWidth;a=a.offsetHeight}b.display=g;b.position=h;b.visibility=d;return new i(c,",
L"a)};function N(a){a=a.parentNode;if(!a)return null;for(;a.nodeType!=1&&!(a.nodeType==9||a.nodeType==11);)a=a.parentNode;return a&&a.nodeType==1?a:null};var O=function(a){a=N(a);if(!a)throw new Error(\"No value given for isDisplayed required parameter\");var c=(a.nodeType==9?a:a.ownerDocument||a.document)?H(a.nodeType==9?a:a.ownerDocument||a.document):window;function b(d,h){if(c.getComputedStyle)return I(d,h);return d.currentStyle?d.currentStyle[h]:null}function g(d){if(b(d,\"display\")==\"none\")return false;d=N(d);return!d||g(d)}if(!(function(d){d.tagName||alert(d);if(d.tagName.toLowerCase()==\"input\"&&d.type.toLowerCase()==\"hidden\")return false;return b(d,",
L"\"visibility\")!=\"hidden\"}(a)&&g(a)))return false;a=M(a);return a.height>0&&a.width>0},P=\"isDisplayed\".split(\".\"),Q=e;!(P[0]in Q)&&Q.execScript&&Q.execScript(\"var \"+P[0]);for(var R;P.length&&(R=P.shift());)if(!P.length&&O!==undefined)Q[R]=O;else Q=Q[R]?Q[R]:(Q[R]={});",
NULL
};

#endif
