// Copyright (c) Google Inc. 2009
// All rights reserved.
// This file is automatically generated by GRIT. Do not edit.
// Built on Fri Mar 06 00:55:37 2009

#pragma once

#define IDR_JSTEMPLATE_JS 29862
